import type { PSEOPage } from "../pages";

export const consultantToolPages: PSEOPage[] = [
  {
    slug: "chatgpt-prompts-for-client-reporting",
    title: "ChatGPT Prompts for Client Reporting — Free | Torvi",
    h1: "ChatGPT prompts for client reporting",
    metaDescription: "ChatGPT prompts for client reports: status updates, progress summaries, risk logs, and exec presentations. Free for consultants.",
    keyword: "chatgpt prompts for client reporting",
    cluster: "consult_ai_tools",
    pageType: "resource_page",
    priorityScore: 44.4,
    body: {
      intro: "Client reports are where consultants earn or lose trust. These prompts give you a consistent, professional starting point for every report type — from the weekly check-in to the end-of-engagement presentation — without the two-hour writing session.",
      whatYouGet: [
        "6 prompts: weekly client status, project milestone summary, risk escalation, findings presentation, exec summary, and engagement close-out",
        "Tone calibration guide for different client types and seniority levels",
        "A guide on feeding project notes and meeting transcripts for accurate, context-rich output",
        "Worked examples from a strategy and process transformation context",
      ],
      whoItsFor: "Independent consultants and small consulting teams who deliver client reports regularly and want a consistent, efficient process that maintains professional quality.",
      ctaNote: "Free prompts. To build a client reporting tool that automates report generation from your project data, the Torvi Consultant track covers it.",
    },
  },
  {
    slug: "client-reporting-template",
    title: "Client Reporting Template — Free Download | Torvi",
    h1: "Client reporting template",
    metaDescription: "A professional client reporting template for consultants. Progress, milestones, risks, decisions, next steps. Free download.",
    keyword: "client reporting template",
    cluster: "consult_ai_tools",
    pageType: "template_page",
    priorityScore: 39.4,
    body: {
      intro: "Client reports that get read have three things in common: they are short, they are structured, and they arrive consistently. This template gives you a format that covers everything your client needs to know without turning into a document nobody opens.",
      whatYouGet: [
        "Client report structure: executive summary, progress against milestones, key decisions made, open risks, and next steps with owners",
        "AI prompt to generate a first-draft report from your project notes",
        "Variants for weekly check-in, monthly steering committee, and end-of-phase review",
        "Worked example from a process transformation engagement",
      ],
      whoItsFor: "Independent consultants and project managers who send regular client reports and want a format that is quick to produce, professional to receive, and consistent across engagements.",
      ctaNote: "Free template. To build a client reporting tool your clients log into directly, the Torvi Consultant track is how.",
    },
  },
  {
    slug: "consulting-statement-of-work-template",
    title: "Consulting Statement of Work Template — Free | Torvi",
    h1: "Consulting statement of work template",
    metaDescription: "A clean SOW template for consultants. Scope, deliverables, timeline, pricing, and exclusions. Free download.",
    keyword: "consulting statement of work template",
    cluster: "consult_ai_tools",
    pageType: "starter_pack",
    priorityScore: 40.5,
    body: {
      intro: "A good SOW prevents 80% of scope creep conversations. It is specific about deliverables, explicit about what is out of scope, and clear about what happens when things change. This template gives you that — a professional format that protects both you and your client.",
      whatYouGet: [
        "SOW structure: project overview, objectives, deliverables, timeline, exclusions, pricing, payment terms, and change management clause",
        "AI prompt to generate a SOW draft from your project briefing notes",
        "Exclusions guide: common scope items that consultants forget to exclude",
        "Worked example from a consulting engagement",
      ],
      whoItsFor: "Independent consultants and small consulting firms who write SOWs regularly and want a template that protects scope without sounding adversarial.",
      ctaNote: "Free template. If you want to build a SOW generation tool that populates from your client intake process, the Torvi Consultant track covers it.",
    },
  },
  {
    slug: "stakeholder-interview-template",
    title: "Stakeholder Interview Template — Free | Torvi",
    h1: "Stakeholder interview template",
    metaDescription: "A structured stakeholder interview template for consultants and PMs. Discussion guide, synthesis format, and follow-up. Free.",
    keyword: "stakeholder interview template",
    cluster: "consult_ai_tools",
    pageType: "template_page",
    priorityScore: 30.0,
    body: {
      intro: "Stakeholder interviews surface the real problem — but only if they are structured well enough to get past surface answers. This template gives you the question framework, the synthesis format, and the follow-up structure to turn interviews into insights.",
      whatYouGet: [
        "Interview discussion guide: opening, context questions, problem depth questions, priority questions, and close",
        "Synthesis template: themes, direct quotes, gaps identified, and follow-up questions",
        "AI prompt to synthesise findings from multiple interview transcripts",
        "Worked example from a process diagnostic",
      ],
      whoItsFor: "Consultants and PMs who run stakeholder discovery phases and want a consistent, structured interview process that produces usable synthesis.",
      ctaNote: "Free template. To build a stakeholder interview and synthesis tool for your practice, the Torvi Consultant track walks you through it.",
    },
  },
  {
    slug: "case-study-template",
    title: "Case Study Template — Free Download | Torvi",
    h1: "Case study template",
    metaDescription: "A consultant case study template covering situation, approach, outcomes, and testimonial. AI prompt included. Free.",
    keyword: "case study template",
    cluster: "consult_ai_tools",
    pageType: "template_page",
    priorityScore: 28.6,
    body: {
      intro: "Case studies are the most persuasive piece of content a consultant can have — and the one most consultants avoid writing because they do not have a format that makes it fast. This template gives you the structure: situation, approach, outcomes, and the quote your client will actually say.",
      whatYouGet: [
        "Case study structure: client context (anonymised), challenge, approach, outcomes (quantified where possible), and client quote",
        "AI prompt to draft a case study from your project notes and outcome data",
        "Anonymisation guide: how to get permission and protect client confidentiality",
        "Worked example from a process transformation case",
      ],
      whoItsFor: "Independent consultants who know they should be publishing case studies but keep deferring because it feels like too much work.",
      ctaNote: "Free template. To build a case study generation tool into your consulting practice, the Torvi Consultant track gives you the path.",
    },
  },
  {
    slug: "discovery-call-template",
    title: "Discovery Call Template — Free | Torvi",
    h1: "Discovery call template",
    metaDescription: "A discovery call template for consultants. Situation questions, problem depth, budget signals, and next steps. Free.",
    keyword: "discovery call template",
    cluster: "consult_ai_tools",
    pageType: "template_page",
    priorityScore: 26.8,
    body: {
      intro: "A good discovery call ends with two things clear: whether you can help, and whether they are serious. This template gives you the question sequence and the notes structure to get to both — without it feeling like an interrogation.",
      whatYouGet: [
        "Discovery call framework: context questions, problem depth questions, urgency signals, budget and timeline, and next step agreement",
        "Pre-call research checklist: what to know before you get on the call",
        "Post-call notes template: summary, qualification score, proposed next step",
        "AI prompt to generate a post-call summary and follow-up email",
      ],
      whoItsFor: "Independent consultants and fractional executives who run discovery calls regularly and want a consistent process that qualifies quickly and converts well.",
      ctaNote: "Free template. To build a discovery and intake tool that streamlines your client qualification process, the Torvi Consultant track covers it.",
    },
  },
  {
    slug: "delivery-tracker-template",
    title: "Delivery Tracker Template — Free | Torvi",
    h1: "Delivery tracker template",
    metaDescription: "A consultant delivery tracker template. Milestones, deliverables, owners, status. One view across your engagement. Free.",
    keyword: "delivery tracker template",
    cluster: "consult_ai_tools",
    pageType: "template_page",
    priorityScore: 23.4,
    body: {
      intro: "Consulting engagements slip not because the work is late, but because nobody has a clear view of what is outstanding. This delivery tracker gives you that view — milestones, deliverables, owners, and status in one place that you can share with your client as a live reference.",
      whatYouGet: [
        "Delivery tracker structure: phases, milestones, deliverables, owners, due dates, status, and completion notes",
        "Weekly update format: what was completed, what is in progress, what is at risk",
        "Client-facing variant: a view that shows progress without exposing internal notes",
        "AI prompt to generate a status update from the tracker",
      ],
      whoItsFor: "Consultants managing multi-week or multi-month engagements who need a simple, shareable way to track deliverables without a complex project management tool.",
      ctaNote: "Free template. To build a client-facing delivery tracking tool, the Torvi Consultant track is the guided path to ship it.",
    },
  },
  {
    slug: "client-diagnostic-template",
    title: "Client Diagnostic Template — Free Download | Torvi",
    h1: "Client diagnostic template",
    metaDescription: "A structured client diagnostic template for consultants. Current state, gaps, root causes, and recommendations. Free.",
    keyword: "client diagnostic template",
    cluster: "consult_ai_tools",
    pageType: "template_page",
    priorityScore: 23.9,
    body: {
      intro: "A client diagnostic done well sets the entire engagement up. Done poorly, you spend the rest of the project correcting misaligned expectations. This template gives you the structure to get it right in the first two weeks: current state, gaps, root causes, and prioritised recommendations.",
      whatYouGet: [
        "Diagnostic structure: scope definition, current state assessment, gap analysis, root cause identification, and prioritised recommendations",
        "Interview synthesis template to feed into the diagnostic findings",
        "AI prompt to generate a diagnostic summary from your assessment notes",
        "Worked example from an ops process diagnostic",
      ],
      whoItsFor: "Consultants and transformation leads who run diagnostic phases at the start of engagements and want a consistent, credible format for findings and recommendations.",
      ctaNote: "Free template. To build a client diagnostic tool that clients complete directly before engagement kick-off, the Torvi Consultant track covers it.",
    },
  },
];
