import type { PSEOPage } from "../pages";

export const extendedIntakePages: PSEOPage[] = [
  {
    slug: "service-request-template",
    title: "Service Request Template — Free Download | Torvi",
    h1: "Service request template",
    metaDescription: "A structured service request template for ops teams. Request type, priority, description, and SLA. Free download.",
    keyword: "service request template",
    cluster: "intake_and_routing",
    pageType: "template_page",
    priorityScore: 23.7,
    body: {
      intro: "Service requests that arrive without structure create triage work. This template standardises the intake so every request arrives with the information needed to classify it, prioritise it, and route it without a clarification step.",
      whatYouGet: [
        "Service request structure: service category, description, business impact, urgency, requester, and SLA expectation",
        "Category taxonomy guide: how to define your service categories for accurate classification",
        "AI prompt to auto-classify and prioritise an incoming service request",
        "Escalation matrix: which request types go to which owner and at what SLA",
      ],
      whoItsFor: "Operations managers and IT leads who manage service requests from internal teams and want a consistent intake format that routes work without manual triage.",
      ctaNote: "Free template. To build an automated service request intake and routing system, the Torvi Ops track covers it.",
    },
  },
  {
    slug: "service-request-automation",
    title: "Service Request Automation — Guide | Torvi",
    h1: "Service request automation",
    metaDescription: "How to automate service request intake: classification, routing, and SLA tracking. Guide for ops and IT teams.",
    keyword: "service request automation",
    cluster: "intake_and_routing",
    pageType: "resource_page",
    priorityScore: 22.8,
    body: {
      intro: "Service request automation removes the bottleneck of manual triage. An automated system classifies the request, checks it for completeness, routes it to the right owner, and starts the SLA clock — without a human in the middle. This guide covers how to build that system.",
      whatYouGet: [
        "Service request automation workflow: submission → classification → validation → routing → SLA start → notification",
        "AI classification prompt design for service request categories",
        "Completeness validation: how to prompt the requester for missing information before routing",
        "Worked example: internal IT service request automation built in three weeks",
      ],
      whoItsFor: "Ops managers and IT leads who manage a service request queue and want to replace manual triage with an automated classification and routing system.",
      ctaNote: "Free guide. The Torvi Ops track gives you the four-week path to build and ship your service request automation.",
    },
  },
  {
    slug: "intake-form-template",
    title: "Intake Form Template — Free Download | Torvi",
    h1: "Intake form template",
    metaDescription: "A lean intake form template for ops teams. Request type, context, priority, and routing. Free download.",
    keyword: "intake form template",
    cluster: "intake_and_routing",
    pageType: "starter_pack",
    priorityScore: 19.0,
    body: {
      intro: "Intake forms that ask for everything get abandoned. Forms that ask too little create follow-up. This template is calibrated for completion: the minimum fields that let you classify, prioritise, and route a request without going back to the requester.",
      whatYouGet: [
        "Intake form fields: request type (dropdown), short description, business impact, required by date, and file attachment",
        "Conditional field logic guide: how to show additional questions based on request type",
        "AI prompt to classify a completed intake form and suggest routing",
        "Variants for project intake, support intake, and change request intake",
      ],
      whoItsFor: "Operations managers who manage intake from multiple internal teams and want a standard form that produces consistently actionable requests.",
      ctaNote: "Free template. To build an automated intake and routing tool from this form, the Torvi Ops track is the four-week path.",
    },
  },
  {
    slug: "client-intake-automation",
    title: "Client Intake Automation — Guide for Consultants | Torvi",
    h1: "Client intake automation",
    metaDescription: "How consultants automate client intake: smart forms, AI synthesis, and briefing generation. Free guide.",
    keyword: "client intake automation",
    cluster: "intake_and_routing",
    pageType: "resource_page",
    priorityScore: 22.4,
    body: {
      intro: "Manual client intake — chasing answers via email, consolidating responses into a brief — takes two to three hours per new engagement. Automation gets that to under 30 minutes: a structured form, AI synthesis of responses, and an auto-generated project brief ready before the first call.",
      whatYouGet: [
        "Client intake automation workflow: intake form → response collection → AI synthesis → project brief generation",
        "Smart form design: conditional questions that adapt based on engagement type",
        "AI prompt to synthesise intake responses into a structured project brief",
        "Worked example: consultant intake process automated for three engagement types",
      ],
      whoItsFor: "Independent consultants and fractional executives who onboard new clients regularly and want to replace the intake email chain with an automated system.",
      ctaNote: "Free guide. To build your client intake automation tool, the Torvi Consultant track gives you the four-week path.",
    },
  },
  {
    slug: "project-intake-automation",
    title: "Project Intake Automation — Guide | Torvi",
    h1: "Project intake automation",
    metaDescription: "How to automate project intake: scoping questions, feasibility check, prioritisation, and routing. Guide for ops and PM teams.",
    keyword: "project intake automation",
    cluster: "intake_and_routing",
    pageType: "resource_page",
    priorityScore: 18.1,
    body: {
      intro: "Project intake automation replaces the back-and-forth of informal request handling with a consistent, automated process. Every project request goes through the same scoping questions, gets evaluated against the same criteria, and routes to the right owner with the right information.",
      whatYouGet: [
        "Project intake automation workflow: request submission → AI scoping → completeness check → prioritisation → routing → acknowledgement",
        "Scoping question set by project type: tool build, process improvement, integration, reporting",
        "Prioritisation prompt: using AI to apply your effort/impact framework consistently",
        "Worked example: cross-functional project intake automated for a BizOps team",
      ],
      whoItsFor: "Operations managers and portfolio leads who receive project requests from across the business and want a consistent, fast intake process that reduces decision time.",
      ctaNote: "Free guide. The Torvi Ops track gives you the four-week guided path to build and ship your project intake automation.",
    },
  },
  {
    slug: "work-request-template",
    title: "Work Request Template — Free Download | Torvi",
    h1: "Work request template",
    metaDescription: "A structured work request template for ops and creative teams. Problem, scope, deadline, and priority. Free download.",
    keyword: "work request template",
    cluster: "intake_and_routing",
    pageType: "starter_pack",
    priorityScore: 19.0,
    body: {
      intro: "Work requests that arrive without context create delays. This template standardises the format so every request has a clear problem statement, defined scope, and a stated deadline — giving the team what they need to start without a clarification meeting.",
      whatYouGet: [
        "Work request structure: request type, problem statement, proposed scope, deadline, priority, and context files",
        "Priority calibration guide: how to help requesters self-assess urgency accurately",
        "AI prompt to review a work request for completeness before it enters the queue",
        "Variants for design, ops, content, and engineering requests",
      ],
      whoItsFor: "Team leads and ops managers who receive work requests from across the business and want a standard format that reduces triage time.",
      ctaNote: "Free template. To automate your work request intake and routing, the Torvi Ops track covers it.",
    },
  },
  {
    slug: "requirements-intake-workflow",
    title: "Requirements Intake Workflow — Guide | Torvi",
    h1: "Requirements intake workflow",
    metaDescription: "How to build a requirements intake workflow: structured intake, AI clarification, and requirements generation. Free guide.",
    keyword: "requirements intake workflow",
    cluster: "intake_and_routing",
    pageType: "resource_page",
    priorityScore: 20.1,
    body: {
      intro: "Requirements intake is where ambiguous feature requests are supposed to become clear specifications. Without a structured workflow, the process relies on whoever handles the request being thorough enough to ask the right questions. A systematic workflow makes that consistency automatic.",
      whatYouGet: [
        "Requirements intake workflow: request submission → AI clarification questions → structured input → requirements generation → review",
        "Clarifying question library by requirement type: feature, integration, reporting, automation",
        "AI prompt to generate requirements from a structured intake response",
        "Worked example: PM team requirements intake workflow from Notion form to Jira ticket",
      ],
      whoItsFor: "Product managers and technical leads who receive requirements from stakeholders and want a consistent intake process that produces complete, actionable requirements without a discovery meeting for every request.",
      ctaNote: "Free guide. To build a requirements intake automation tool, the Torvi PM track is the four-week path.",
    },
  },
  {
    slug: "ai-intake-form-tool",
    title: "AI Intake Form Tool — Guide | Torvi",
    h1: "AI intake form tool",
    metaDescription: "How to build an AI-powered intake form that asks follow-up questions, classifies requests, and routes automatically.",
    keyword: "ai intake form tool",
    cluster: "intake_and_routing",
    pageType: "resource_page",
    priorityScore: 19.1,
    body: {
      intro: "An AI intake form does something a static form cannot: it adapts based on what the requester enters. If a description is vague, it asks a follow-up question. If the category is ambiguous, it asks for clarification. The result is a completed intake that requires no triage follow-up.",
      whatYouGet: [
        "AI intake form architecture: static intake layer + AI validation + dynamic clarification + classification + routing",
        "Prompt design for intake validation and clarification question generation",
        "Build options: form builder with AI integration vs. custom build",
        "Worked example: HR intake form with AI-driven completeness checking",
      ],
      whoItsFor: "Ops managers who manage high-volume request intake and want to eliminate the back-and-forth of incomplete requests without making the form longer.",
      ctaNote: "Free guide. To build your AI intake form tool, the Torvi Ops track gives you the four-week guided path.",
    },
  },
];
