import type { PSEOPage } from "../pages";

export const extendedConsultPages: PSEOPage[] = [
  {
    slug: "consultant-proposal-template",
    title: "Consultant Proposal Template — Free Download | Torvi",
    h1: "Consultant proposal template",
    metaDescription: "A professional consultant proposal template. Situation, approach, deliverables, pricing, and timeline. Free download.",
    keyword: "consultant proposal template",
    cluster: "consult_ai_tools",
    pageType: "guide_page",
    priorityScore: 24.7,
    body: {
      intro: "A proposal that wins business is specific about the problem, credible about the approach, and clear about the outcome. Generic proposals lose to whoever sounds most confident. This template forces the specificity that makes yours stand out.",
      whatYouGet: [
        "Proposal structure: situation summary, proposed approach, deliverables, timeline, investment, and next step",
        "AI prompt to generate a proposal first draft from your discovery call notes",
        "Pricing presentation guide: how to present fees in a way that anchors on value",
        "Worked example from an ops transformation proposal",
      ],
      whoItsFor: "Independent consultants and small consulting firms who write proposals regularly and want a format that is fast to produce and consistently professional.",
      ctaNote: "Free template. To build a proposal generation tool for your practice, the Torvi Consultant track covers it.",
    },
  },
  {
    slug: "ai-delivery-tracker-tool",
    title: "AI Delivery Tracker — Guide for Consultants | Torvi",
    h1: "AI delivery tracker",
    metaDescription: "How consultants use AI to track and report on delivery progress. Tools, prompts, and templates for engagement management.",
    keyword: "ai delivery tracker tool",
    cluster: "consult_ai_tools",
    pageType: "resource_page",
    priorityScore: 24.9,
    body: {
      intro: "Delivery tracking for consultants has two jobs: keeping you on top of what is outstanding, and keeping your client informed of progress without a 30-minute update call. AI handles the second job well — generating progress summaries from your tracker data so you can focus on the delivery.",
      whatYouGet: [
        "Delivery tracker structure: phases, milestones, deliverables, status, and completion notes",
        "AI prompt to generate a client-facing progress summary from your tracker",
        "Weekly delivery review format: what to check every Monday morning",
        "Escalation logic: when to escalate a risk before the client notices",
      ],
      whoItsFor: "Consultants managing multi-week engagements who want a simple system for tracking delivery and generating client-ready progress updates without manual writing.",
      ctaNote: "Free guide. To build a delivery tracking tool for your consulting practice, the Torvi Consultant track is the path.",
    },
  },
  {
    slug: "meeting-summary-template",
    title: "Meeting Summary Template — Free | Torvi",
    h1: "Meeting summary template",
    metaDescription: "A clean meeting summary template for consultants and project teams. Decisions, actions, context. Ready to send. Free.",
    keyword: "meeting summary template",
    cluster: "consult_ai_tools",
    pageType: "template_page",
    priorityScore: 18.4,
    body: {
      intro: "Meeting summaries sent within an hour of a meeting are read. Summaries sent the next day are ignored. This template is designed for speed: a clear structure you can fill in during the meeting and send immediately after.",
      whatYouGet: [
        "Meeting summary structure: key points, decisions made, action items (owner + due date), and open questions",
        "AI prompt to generate a summary from rough notes or a transcript",
        "Consulting-specific variant: client-facing meeting summary with professional tone",
        "Worked example from a client workshop",
      ],
      whoItsFor: "Consultants and project managers who send meeting summaries to clients and internal stakeholders and want a consistent, fast format.",
      ctaNote: "Free template. To build a meeting summary automation tool, the Torvi Consultant or Ops track covers it.",
    },
  },
  {
    slug: "workshop-agenda-template",
    title: "Workshop Agenda Template — Free | Torvi",
    h1: "Workshop agenda template",
    metaDescription: "A structured workshop agenda template for consultants. Objectives, sessions, timebox, and facilitation notes. Free.",
    keyword: "workshop agenda template",
    cluster: "consult_ai_tools",
    pageType: "starter_pack",
    priorityScore: 17.3,
    body: {
      intro: "A workshop without a structured agenda is a meeting that goes over time and produces vague outputs. This template gives you the structure that keeps workshops on track: session objectives, timeboxes, facilitation method, and explicit output for each block.",
      whatYouGet: [
        "Workshop agenda structure: objectives, session blocks (objective, method, timebox, output), and wrap-up/next steps",
        "Facilitation notes format: what the facilitator needs to know for each session",
        "AI prompt to generate a workshop agenda from a brief or objectives list",
        "Worked example: discovery workshop agenda for a process transformation engagement",
      ],
      whoItsFor: "Consultants and transformation leads who design and facilitate client workshops and want a consistent agenda format that produces clear, actionable outputs.",
      ctaNote: "Free template. To build a workshop design and facilitation tool, the Torvi Consultant track is the guided path.",
    },
  },
  {
    slug: "consulting-proposal-template",
    title: "Consulting Proposal Template — Free Download | Torvi",
    h1: "Consulting proposal template",
    metaDescription: "A consulting proposal template for independent consultants. Problem statement, approach, timeline, fees. Professional and fast to write. Free.",
    keyword: "consulting proposal template",
    cluster: "consult_ai_tools",
    pageType: "template_page",
    priorityScore: 13.7,
    body: {
      intro: "Consulting proposals that win have one thing in common: they demonstrate that you understood the client's actual problem, not just the one they described in the brief. This template builds that demonstration into the structure.",
      whatYouGet: [
        "Consulting proposal format: situation analysis, proposed approach, scope of work, investment, timeline, and next steps",
        "AI prompt to generate a proposal draft from your discovery notes",
        "Win/loss analysis questions to sharpen your proposal approach",
        "Worked example from a process improvement engagement",
      ],
      whoItsFor: "Independent consultants who write proposals for new engagements and want a professional, consistent format that is faster to produce without feeling templated.",
      ctaNote: "Free template. To build a proposal generation tool for your practice, the Torvi Consultant track covers it.",
    },
  },
  {
    slug: "consultant-delivery-tracker-template",
    title: "Consultant Delivery Tracker Template — Free | Torvi",
    h1: "Consultant delivery tracker template",
    metaDescription: "A delivery tracker template for consultants. Phases, milestones, status, and client-facing view. Free download.",
    keyword: "consultant delivery tracker template",
    cluster: "consult_ai_tools",
    pageType: "guide_page",
    priorityScore: 21.3,
    body: {
      intro: "Delivery trackers exist to prevent the worst consulting conversation: a client who is surprised that something is late. This template gives you a shared view of delivery status that keeps your client informed and your engagement on track.",
      whatYouGet: [
        "Delivery tracker: phases, milestones, deliverables, owners, due dates, status (RAG), and notes",
        "Client-facing variant: a clean view that shows progress without internal notes",
        "Weekly update process: how to maintain the tracker without it becoming a burden",
        "AI prompt to generate a client update email from the tracker status",
      ],
      whoItsFor: "Consultants managing engagements with multiple deliverables and timelines who want a simple tracker they can share with clients as a live progress reference.",
      ctaNote: "Free template. To build a client-facing delivery tracking tool, the Torvi Consultant track is the guided path.",
    },
  },
  {
    slug: "ai-for-consulting",
    title: "AI for Consulting — What Actually Works | Torvi",
    h1: "AI for consulting",
    metaDescription: "A practical guide to AI for consultants: where it saves time, where it does not, and how to build it into your practice.",
    keyword: "ai for consulting",
    cluster: "consult_ai_tools",
    pageType: "resource_page",
    priorityScore: 20.3,
    body: {
      intro: "AI is changing consulting work — but not in the way most articles claim. The value is not in replacing analysis; it is in eliminating the formatting, drafting, and documentation work that takes up 40% of most consultants' time. This guide shows you where to apply it.",
      whatYouGet: [
        "AI use case map for consulting: where it saves the most time (proposals, reports, summaries, templates) vs. where human judgment is irreplaceable",
        "Practice-building AI toolkit: the tools and workflows that experienced consultants are actually using",
        "Client communication strategy: how to use AI without losing the personal tone clients expect",
        "A 4-week implementation plan for integrating AI into your consulting practice",
      ],
      whoItsFor: "Independent consultants and fractional executives who want a clear, practical guide to deploying AI in their practice without hype or oversimplification.",
      ctaNote: "Free guide. To go beyond using AI tools and start building tools for your practice, the Torvi Consultant track is the path.",
    },
  },
  {
    slug: "statement-of-work-template",
    title: "Statement of Work Template — Free Download | Torvi",
    h1: "Statement of work template",
    metaDescription: "A professional statement of work template for consultants and project teams. Scope, deliverables, timeline, and fees. Free.",
    keyword: "statement of work template",
    cluster: "consult_ai_tools",
    pageType: "template_page",
    priorityScore: 17.8,
    body: {
      intro: "A statement of work that prevents scope creep is specific about what is included, what is not, and what happens when either party wants to change it. This template gives you that specificity without the adversarial tone.",
      whatYouGet: [
        "SOW structure: project background, objectives, scope of work, deliverables, exclusions, timeline, fees, change management, and acceptance criteria",
        "AI prompt to generate a SOW from your project briefing notes",
        "Exclusions guide: items consultants commonly forget to exclude from scope",
        "Worked example from a strategy consulting engagement",
      ],
      whoItsFor: "Independent consultants and project managers who write SOWs for client engagements and want a format that protects scope without being unnecessarily legalistic.",
      ctaNote: "Free template. To build a SOW generation tool integrated with your intake process, the Torvi Consultant track covers it.",
    },
  },
];
