import type { PSEOPage } from "../pages";

export const extendedMeetingsPages: PSEOPage[] = [
  {
    slug: "ai-sprint-planning-tool",
    title: "AI Sprint Planning — Guide and Templates | Torvi",
    h1: "AI sprint planning tool",
    metaDescription: "How to use AI for sprint planning: backlog preparation, capacity calculation, and sprint summary generation. Guide and templates.",
    keyword: "ai sprint planning tool",
    cluster: "meetings_and_action_items",
    pageType: "template_page",
    priorityScore: 40.6,
    body: {
      intro: "Sprint planning takes too long because backlog items arrive at the meeting in different states of readiness. AI can fix the preparation side — reviewing items for completeness, estimating effort, and generating the sprint goal statement — so the meeting itself is shorter and more decisive.",
      whatYouGet: [
        "Sprint planning prep workflow: backlog review → completeness check → AI effort flagging → capacity calculation",
        "Prompts for: sprint goal draft, item breakdown, and post-sprint velocity summary",
        "Sprint planning meeting agenda template: structured for a 90-minute session that ends with a committed sprint",
        "Worked example: sprint planning for a PM-built internal tool team",
      ],
      whoItsFor: "Product managers and engineering leads who run sprint planning and want to reduce the meeting time and the prep time without losing plan quality.",
      ctaNote: "Free guide and templates. To build a sprint planning tool your team uses, the Torvi PM track covers it.",
    },
  },
  {
    slug: "retrospective-generator",
    title: "Retrospective Generator — AI-Assisted Retros | Torvi",
    h1: "Retrospective generator",
    metaDescription: "How to use AI to run better retrospectives: async input synthesis, theme identification, and action generation. Guide and template.",
    keyword: "retrospective generator",
    cluster: "meetings_and_action_items",
    pageType: "resource_page",
    priorityScore: 26.5,
    body: {
      intro: "The hardest part of a retrospective is getting honest, specific input and then turning it into actions that actually change behaviour. AI helps with both: collecting async input, identifying themes across responses, and generating a prioritised action set that the team commits to.",
      whatYouGet: [
        "Async retro workflow: input collection → AI theme synthesis → prioritisation → action assignment",
        "AI prompts for: synthesising retro input, identifying root causes, and generating improvement actions",
        "Retro formats covered: Start/Stop/Continue, 4Ls, Mad/Sad/Glad, and simple team retro",
        "Worked example: distributed team retro synthesised from async Notion input",
      ],
      whoItsFor: "Team leads and Scrum Masters who run retrospectives and want a process that produces real actions, not just a shared document of complaints.",
      ctaNote: "Free guide. To build a retrospective and continuous improvement tool for your team, the Torvi Ops track is the path.",
    },
  },
  {
    slug: "meeting-notes-automation",
    title: "Meeting Notes Automation — Guide | Torvi",
    h1: "Meeting notes automation",
    metaDescription: "How to automate meeting notes end to end: transcription, AI summarisation, action extraction, and routing. Free guide.",
    keyword: "meeting notes automation",
    cluster: "meetings_and_action_items",
    pageType: "resource_page",
    priorityScore: 24.0,
    body: {
      intro: "Full meeting notes automation is a three-layer system: record (transcription), extract (AI summarisation and action items), and route (send structured notes to the right place). Most people only have layer one. This guide covers how to build all three.",
      whatYouGet: [
        "Meeting notes automation stack: transcription tool → AI extraction prompt → structured output → routing to PM/ops tool",
        "Prompt design for different meeting types: project reviews, 1:1s, standup, and stakeholder sync",
        "Routing logic: how to get action items into Linear, Asana, or Notion automatically based on content",
        "Worked example: full meeting notes pipeline for a product team",
      ],
      whoItsFor: "PMs and ops leads who attend multiple meetings daily and want a system that captures, structures, and routes everything without manual effort.",
      ctaNote: "Free guide. To build a custom meeting notes automation tool, the Torvi PM or Ops track gives you the guided path.",
    },
  },
  {
    slug: "meeting-agenda-generator",
    title: "Meeting Agenda Generator — AI Guide | Torvi",
    h1: "Meeting agenda generator",
    metaDescription: "How to use AI to generate meeting agendas from objectives and context. Prompts, templates, and worked examples. Free.",
    keyword: "meeting agenda generator",
    cluster: "meetings_and_action_items",
    pageType: "resource_page",
    priorityScore: 23.8,
    body: {
      intro: "Generating a meeting agenda with AI takes about 30 seconds when you have the right prompt. The result is a structured agenda with objectives, timebox, owner, and expected output for each item — better than most manually written agendas, in a fraction of the time.",
      whatYouGet: [
        "Meeting agenda generation prompt: input context, meeting type, attendees, and required outputs → structured agenda",
        "Variants by meeting type: project review, stakeholder sync, 1:1, retrospective, and planning meeting",
        "AI prompt to generate a pre-read document alongside the agenda",
        "Worked example: project kickoff agenda generated from a brief",
      ],
      whoItsFor: "Team leads and PMs who prepare agendas for multiple meeting types and want a consistent, fast process that produces better agendas than writing from scratch.",
      ctaNote: "Free guide. To build a meeting management tool for your team, the Torvi Ops track covers it.",
    },
  },
  {
    slug: "meeting-agenda-software",
    title: "Meeting Agenda Software — What to Use | Torvi",
    h1: "Meeting agenda software",
    metaDescription: "A guide to meeting agenda software and AI tools for structured meetings. What to use, what to build, and when.",
    keyword: "meeting agenda software",
    cluster: "meetings_and_action_items",
    pageType: "resource_page",
    priorityScore: 22.8,
    body: {
      intro: "Meeting agenda software ranges from lightweight templates to full meeting management platforms. The right choice depends on your team's process maturity and the types of meetings you run. This guide cuts through the options and makes the choice clear.",
      whatYouGet: [
        "Tool comparison: Notion, Coda, Fellow, and AI-native meeting tools — what each does well",
        "When to use a dedicated meeting tool vs. a general-purpose doc",
        "When to build a custom meeting tool for your team's specific workflow",
        "A meeting management system design guide for ops-heavy teams",
      ],
      whoItsFor: "Team leads and ops managers evaluating meeting tools who want a clear recommendation based on their team's specific context.",
      ctaNote: "Free guide. To build a custom meeting management tool for your team, the Torvi Ops track is the guided path.",
    },
  },
  {
    slug: "ai-meeting-minutes-tool",
    title: "AI Meeting Minutes — Tool Guide | Torvi",
    h1: "AI meeting minutes tool",
    metaDescription: "How AI meeting minutes tools work and how to choose or build the right one for your team. Practical guide.",
    keyword: "ai meeting minutes tool",
    cluster: "meetings_and_action_items",
    pageType: "resource_page",
    priorityScore: 20.8,
    body: {
      intro: "AI meeting minutes tools have matured significantly — the best ones now produce minutes that require minimal editing. The decision is no longer whether to use AI for minutes, but which tool fits your workflow and whether the off-the-shelf options cover your specific needs.",
      whatYouGet: [
        "How AI meeting minutes tools work: transcription, summarisation, and action extraction",
        "Tool comparison: Otter, Fireflies, Notion AI, and custom builds — what each does well",
        "When to use an existing tool vs. build a custom solution for your team",
        "A guide to getting consistent, high-quality minutes output from any AI tool",
      ],
      whoItsFor: "Ops managers and team leads evaluating meeting minutes tools who want a clear, unbiased guide to the options and their trade-offs.",
      ctaNote: "Free guide. To build a custom meeting minutes tool for your specific workflow, the Torvi Ops track is how.",
    },
  },
  {
    slug: "project-update-template",
    title: "Project Update Template — Free Download | Torvi",
    h1: "Project update template",
    metaDescription: "A lean project update template for teams and stakeholders. Progress, blockers, next steps. Free download.",
    keyword: "project update template",
    cluster: "meetings_and_action_items",
    pageType: "starter_pack",
    priorityScore: 18.7,
    body: {
      intro: "Project updates fail when they are too long, too infrequent, or too focused on what happened rather than what to do next. This template fixes all three: a short, structured format that focuses on current state, blockers, and required actions.",
      whatYouGet: [
        "Project update structure: status (RAG), progress this period, key decisions, blockers (with owners), and next steps",
        "Frequency guide: when to send weekly vs. biweekly vs. milestone-based updates",
        "AI prompt to generate an update from your project notes and last update",
        "Variants for internal team, stakeholder, and client audiences",
      ],
      whoItsFor: "Project managers and team leads who send recurring project updates and want a consistent, fast format that keeps everyone informed without becoming a reporting burden.",
      ctaNote: "Free template. To automate project update generation from your project data, the Torvi PM or Ops track covers it.",
    },
  },
  {
    slug: "project-update-automation",
    title: "Project Update Automation — Guide | Torvi",
    h1: "Project update automation",
    metaDescription: "How to automate project updates: data extraction, AI summarisation, and stakeholder distribution. Free guide.",
    keyword: "project update automation",
    cluster: "meetings_and_action_items",
    pageType: "resource_page",
    priorityScore: 19.9,
    body: {
      intro: "Project update automation is one of the most straightforward wins in ops and PM tooling. The data already exists in your project management tool — the work is extracting the right subset, summarising it clearly, and distributing it without manual intervention.",
      whatYouGet: [
        "Update automation workflow: project tool → data extraction → AI summarisation → structured update → distribution",
        "Integration patterns for Jira, Linear, Notion, and Asana as data sources",
        "AI prompt for generating a stakeholder-ready project update from raw task data",
        "Worked example: automated weekly project update from a Linear workspace",
      ],
      whoItsFor: "PMs and project leads who send weekly project updates to stakeholders and want to replace the manual write-up with an automated workflow.",
      ctaNote: "Free guide. To build and ship your project update automation tool, the Torvi PM track gives you the four-week guided path.",
    },
  },
  {
    slug: "standup-notes-automation",
    title: "Standup Notes Automation — Guide | Torvi",
    h1: "Standup notes automation",
    metaDescription: "How to automate standup notes: async collection, AI summarisation, and routing to your team channel. Free guide.",
    keyword: "standup notes automation",
    cluster: "meetings_and_action_items",
    pageType: "resource_page",
    priorityScore: 19.6,
    body: {
      intro: "Async standups work better than live standups for most distributed teams — but only if the synthesis step is automated. Manually reading 12 standup posts and extracting the blockers every morning defeats the purpose. This guide covers how to automate the full cycle.",
      whatYouGet: [
        "Async standup automation: collection (Slack form or Notion template) → AI summarisation → blockers extraction → team broadcast",
        "Prompts for generating a team standup summary from individual updates",
        "Blocker identification and routing: how to surface blockers that need action",
        "Worked example: team of 8 async standup automated with Notion + ChatGPT",
      ],
      whoItsFor: "Team leads and ops managers running async standups who spend too much time manually synthesising the daily updates.",
      ctaNote: "Free guide. To build a standup automation tool for your team, the Torvi Ops track covers it.",
    },
  },
  {
    slug: "weekly-planning-software",
    title: "Weekly Planning with AI — Guide | Torvi",
    h1: "Weekly planning software",
    metaDescription: "How to use AI for weekly planning: priority setting, time blocking, and end-of-week review. Guide for senior professionals.",
    keyword: "weekly planning software",
    cluster: "meetings_and_action_items",
    pageType: "resource_page",
    priorityScore: 21.2,
    body: {
      intro: "The best weekly planning system is the one you actually use. For most senior professionals, that means a 15-minute process that sets clear priorities, maps them to time, and leaves room for the unexpected. AI can structure that process — not replace it.",
      whatYouGet: [
        "Weekly planning workflow: last week review → priority identification → calendar mapping → daily task list",
        "AI prompts for: distilling priorities from your task list, identifying conflicts, and generating a daily plan",
        "Tool comparison: which planning tools work well with AI assistance",
        "Worked example: a senior PM's weekly planning process using Notion and ChatGPT",
      ],
      whoItsFor: "Senior professionals who want a consistent weekly planning practice that keeps them focused and adapts to their actual workload.",
      ctaNote: "Free guide. To build a weekly planning tool for your team, the Torvi run gives you the four-week path.",
    },
  },
  {
    slug: "sprint-planning-template",
    title: "Sprint Planning Template — Free | Torvi",
    h1: "Sprint planning template",
    metaDescription: "A structured sprint planning template: goal, capacity, backlog selection, and commitments. Free for PM and eng teams.",
    keyword: "sprint planning template",
    cluster: "meetings_and_action_items",
    pageType: "starter_pack",
    priorityScore: 12.8,
    body: {
      intro: "Sprint planning works when the inputs are prepared and the outputs are explicit. This template structures both — a pre-meeting checklist that ensures backlog items are ready, and a sprint plan document that records the goal, capacity, commitments, and assumptions.",
      whatYouGet: [
        "Sprint planning document: sprint goal, capacity (hours/points), committed items, out-of-scope items, assumptions, and risks",
        "Pre-meeting checklist: item readiness criteria before sprint planning starts",
        "AI prompt to generate a sprint goal statement from the committed backlog",
        "Post-sprint review template that feeds into the next sprint plan",
      ],
      whoItsFor: "Product managers and engineering leads who run two-week sprints and want a planning process that starts and ends the session with clarity.",
      ctaNote: "Free template. To build a sprint planning tool for your team, the Torvi PM track covers it.",
    },
  },
];
