import type { PSEOPage } from "../pages";

export const extendedOpsPages: PSEOPage[] = [
  {
    slug: "operations-automation-tools-online",
    title: "Operations Automation Tools — Guide for Ops Teams | Torvi",
    h1: "Operations automation tools",
    metaDescription: "A practical guide to operations automation tools: what to evaluate, what to build, and when each approach makes sense.",
    keyword: "operations automation tools online",
    cluster: "ops_ai_tools",
    pageType: "resource_page",
    priorityScore: 31.0,
    body: {
      intro: "Operations automation is a spectrum from off-the-shelf tools to custom builds. Most ops teams benefit from a mix — configured tools for standard workflows, custom builds for the specific processes that make their function unique. This guide helps you decide where each approach applies.",
      whatYouGet: [
        "Tool categories: RPA, workflow automation, AI-native tools, and lightweight app builders — what each does well",
        "Decision framework: configure vs. build vs. buy — when each option wins",
        "The five ops automation use cases with the highest ROI in 2024–2025",
        "A short evaluation checklist for any ops tool you are considering",
      ],
      whoItsFor: "Operations managers evaluating automation options who want a practical framework for decision-making, not a vendor comparison article.",
      ctaNote: "Free guide. If you want to build the custom automation your ops function actually needs, the Torvi Ops track is the four-week path to ship it.",
    },
  },
  {
    slug: "intake-template",
    title: "Intake Template — Free Download for Ops Teams | Torvi",
    h1: "Intake template",
    metaDescription: "A clean intake template for ops teams. Request type, priority, context, and routing fields. Free download.",
    keyword: "intake template",
    cluster: "ops_ai_tools",
    pageType: "starter_pack",
    priorityScore: 32.6,
    body: {
      intro: "Intake forms that capture too little create back-and-forth. Forms that ask too much create abandonment. This template finds the balance — the minimum fields needed to classify, route, and action a request without delay.",
      whatYouGet: [
        "Intake form structure: request type, description, urgency, context, and requester details",
        "Routing logic guide: how to map request types to owners and SLAs",
        "AI prompt to classify and route an incoming request automatically",
        "Variants for project intake, support intake, and change request intake",
      ],
      whoItsFor: "Operations managers who handle incoming requests from across the business and want a consistent, fast intake process that routes work to the right place every time.",
      ctaNote: "Free template. To build an automated intake and routing tool, the Torvi Ops track covers it in Weeks 1–2.",
    },
  },
  {
    slug: "request-intake-template",
    title: "Request Intake Template — Free Download | Torvi",
    h1: "Request intake template",
    metaDescription: "A structured request intake template for ops and project teams. Type, priority, scope, and routing. Free.",
    keyword: "request intake template",
    cluster: "ops_ai_tools",
    pageType: "template_page",
    priorityScore: 30.6,
    body: {
      intro: "Request intake is the front door of your ops function. When the form is well-structured, requests arrive with enough context to action immediately. When it is not, every request kicks off a clarification email chain. This template fixes the form.",
      whatYouGet: [
        "Request intake structure: request type, problem description, business impact, urgency, required by date, and relevant context",
        "Intake validation checklist: what to check before a request enters the queue",
        "AI prompt to auto-generate a routing decision from a completed intake form",
        "Worked example for an ops function handling requests from five internal teams",
      ],
      whoItsFor: "Operations leads and project managers who receive requests from multiple teams and want to standardise the intake so requests arrive complete and routable.",
      ctaNote: "Free template. To automate your request intake process end to end, the Torvi Ops track gives you the guided four-week path.",
    },
  },
  {
    slug: "workflow-automation-template",
    title: "Workflow Automation Template — Free | Torvi",
    h1: "Workflow automation template",
    metaDescription: "A workflow automation planning template. Trigger, steps, conditions, error handling, and monitoring. Free download.",
    keyword: "workflow automation template",
    cluster: "ops_ai_tools",
    pageType: "template_page",
    priorityScore: 26.5,
    body: {
      intro: "Most workflow automations fail at the planning stage — not the build stage. They are designed for the happy path and break on the first exception. This template forces comprehensive planning: trigger, steps, conditions, error states, and monitoring, all defined before you write a line of logic.",
      whatYouGet: [
        "Workflow automation plan: trigger definition, step-by-step logic, conditions and branches, error handling, and monitoring approach",
        "Edge case capture: 10 questions your automation plan must answer before you build",
        "Integration spec template for connecting to external tools",
        "Worked example: project intake to Notion routing automation",
      ],
      whoItsFor: "Ops managers and process owners planning workflow automation who want to reduce re-work by getting the design right before the build starts.",
      ctaNote: "Free template. To build and ship your workflow automation in four weeks, the Torvi Ops track gives you the guided path.",
    },
  },
  {
    slug: "ai-task-routing-tool",
    title: "AI Task Routing — Guide and Templates | Torvi",
    h1: "AI task routing tool",
    metaDescription: "How to build an AI-powered task routing tool: classification, rules engine, and assignment logic. Guide for ops teams.",
    keyword: "ai task routing tool",
    cluster: "ops_ai_tools",
    pageType: "resource_page",
    priorityScore: 24.7,
    body: {
      intro: "AI task routing replaces the judgment calls that slow down ops queues. Instead of a human reading every incoming request and deciding where it goes, the AI classifies it, applies your routing rules, and assigns it — in seconds. This guide covers how to build that system.",
      whatYouGet: [
        "Task routing system components: intake capture, AI classification, rules engine, assignment, and escalation",
        "Classification prompt design for your specific request types",
        "Rules engine template: if/then logic for routing decisions",
        "Worked example: internal IT helpdesk routing built with AI classification",
      ],
      whoItsFor: "Ops managers who manage a task or request queue and want to eliminate manual triage without losing routing accuracy.",
      ctaNote: "Free guide. To build your task routing tool in four weeks, the Torvi Ops track is the guided path.",
    },
  },
  {
    slug: "request-intake-automation-tool",
    title: "Request Intake Automation — Guide | Torvi",
    h1: "Request intake automation",
    metaDescription: "How to automate request intake: smart forms, AI classification, and routing to the right owner. Guide for ops teams.",
    keyword: "request intake automation tool",
    cluster: "ops_ai_tools",
    pageType: "resource_page",
    priorityScore: 26.0,
    body: {
      intro: "Request intake automation removes the manual step of reading every request and deciding what it is and where it goes. The system takes an incoming request, classifies it, validates it for completeness, and routes it to the right owner — without a human in the middle.",
      whatYouGet: [
        "Automation workflow: request submission → AI classification → completeness check → routing → SLA assignment",
        "Smart intake form design: using conditional logic to capture the right context by request type",
        "Classification prompt for common request categories",
        "Escalation logic template: what happens when the AI is not confident",
      ],
      whoItsFor: "Operations managers building intake automation for the first time who want a clear blueprint before they start building.",
      ctaNote: "Free guide. The Torvi Ops track gives you a four-week guided path to ship your intake automation.",
    },
  },
  {
    slug: "ai-request-intake-tool",
    title: "AI Request Intake Tool — Guide | Torvi",
    h1: "AI request intake tool",
    metaDescription: "How to build an AI-powered request intake tool that auto-classifies, validates, and routes incoming requests.",
    keyword: "ai request intake tool",
    cluster: "ops_ai_tools",
    pageType: "resource_page",
    priorityScore: 24.4,
    body: {
      intro: "An AI request intake tool does three things a manual form cannot: it asks follow-up questions when a request is incomplete, it classifies the request type automatically, and it routes to the right owner without a human queue manager. This guide shows you how to build one.",
      whatYouGet: [
        "Tool architecture: intake form, classification layer, validation logic, routing engine, and notification",
        "AI prompt design for classification and clarification question generation",
        "Integration options: Slack, email, and web form intake",
        "Worked example: consultant project intake built and deployed in three weeks",
      ],
      whoItsFor: "Ops managers who want to replace a manual intake queue with an automated system that handles the triage work.",
      ctaNote: "Free guide. The Torvi Ops track is the four-week path to ship this.",
    },
  },
  {
    slug: "ai-operations-tools",
    title: "AI Tools for Operations — A Practical Overview | Torvi",
    h1: "AI operations tools",
    metaDescription: "A practical overview of AI tools for operations teams: automation, reporting, intake, routing, and documentation. What to use and when.",
    keyword: "ai operations tools",
    cluster: "ops_ai_tools",
    pageType: "resource_page",
    priorityScore: 22.6,
    body: {
      intro: "The AI tools landscape for operations is noisy. Most are either overpowered general-purpose platforms or underpowered automation tools that cannot handle real operational complexity. This guide cuts through the noise and maps the tools that actually work for core ops use cases.",
      whatYouGet: [
        "Tool map by use case: intake, routing, reporting, documentation, scheduling, and communication",
        "Off-the-shelf vs. custom decision guide for each category",
        "The ten operational workflows where AI delivers measurable time savings",
        "Evaluation framework: how to assess any AI tool before committing",
      ],
      whoItsFor: "Operations managers who want a clear, opinionated view of the AI tools landscape for their function — without a sales pitch.",
      ctaNote: "Free guide. If you want to build the specific tool your ops team needs, the Torvi Ops track gives you the four-week path.",
    },
  },
  {
    slug: "weekly-reporting-template",
    title: "Weekly Reporting Template — Free Download | Torvi",
    h1: "Weekly reporting template",
    metaDescription: "A structured weekly reporting template for ops and PM teams. KPIs, progress, blockers, next week. Free download.",
    keyword: "weekly reporting template",
    cluster: "ops_ai_tools",
    pageType: "template_page",
    priorityScore: 21.8,
    body: {
      intro: "Weekly reports should take 15 minutes to produce and two minutes to read. This template is designed around that constraint — a lean format that covers what changed, what matters, and what is coming, without turning into a status novel.",
      whatYouGet: [
        "Weekly report structure: headline status, KPI snapshot, key wins, blockers, and next week's priorities",
        "AI prompt to generate a weekly report from your notes and task tool",
        "Variants for team reports, executive updates, and client-facing weeklies",
        "Distribution guide: format and channel by audience",
      ],
      whoItsFor: "Ops managers and team leads who send weekly reports to multiple audiences and want a format that is fast to produce and consistently useful to receive.",
      ctaNote: "Free template. To automate your weekly reporting workflow, the Torvi Ops track covers it.",
    },
  },
  {
    slug: "kpi-dashboard-template",
    title: "KPI Dashboard Template — Free | Torvi",
    h1: "KPI dashboard template",
    metaDescription: "A KPI dashboard template for ops and leadership teams. Metrics, targets, RAG status, and trends. Free download.",
    keyword: "kpi dashboard template",
    cluster: "ops_ai_tools",
    pageType: "starter_pack",
    priorityScore: 12.4,
    body: {
      intro: "A KPI dashboard that shows everything is a dashboard that highlights nothing. This template starts with a constraint: five metrics that matter, each with a target, a current value, a RAG status, and a trend. Everything else is appendix.",
      whatYouGet: [
        "KPI dashboard structure: primary metrics (target, actual, RAG), trend chart placeholders, variance commentary, and alert conditions",
        "Metric selection guide: how to choose the five numbers that drive your function",
        "AI prompt to generate weekly KPI commentary from your data",
        "Variants for ops, product, revenue, and people dashboards",
      ],
      whoItsFor: "Operations managers and team leads who need a dashboard their leadership team will actually read and act on.",
      ctaNote: "Free template. To build a live KPI dashboard that populates automatically, the Torvi Ops track is how.",
    },
  },
  {
    slug: "approvals-workflow-template",
    title: "Approvals Workflow Template — Free | Torvi",
    h1: "Approvals workflow template",
    metaDescription: "A structured approvals workflow template. Request, review, decision, notify. Free download for ops teams.",
    keyword: "approvals workflow template",
    cluster: "ops_ai_tools",
    pageType: "starter_pack",
    priorityScore: 12.8,
    body: {
      intro: "Approvals workflows break down when the request format is inconsistent, the approver is unclear, or the status is invisible. This template fixes all three: a standard request format, defined approver by type, and a visible status at every stage.",
      whatYouGet: [
        "Approvals workflow structure: request submission, review checklist, approval/rejection decision, and requester notification",
        "Approver assignment matrix: who approves what by request type and value",
        "AI prompt to check a request for completeness before routing to an approver",
        "Escalation logic for stalled approvals",
      ],
      whoItsFor: "Ops managers and Chiefs of Staff who manage approval workflows across multiple functions and want a consistent process that does not require chasing people.",
      ctaNote: "Free template. To build an automated approvals tool, the Torvi Ops track covers it.",
    },
  },
  {
    slug: "vendor-management-template",
    title: "Vendor Management Template — Free | Torvi",
    h1: "Vendor management template",
    metaDescription: "A vendor management template for ops teams. Contracts, contacts, performance tracking, and renewal dates. Free.",
    keyword: "vendor management template",
    cluster: "ops_ai_tools",
    pageType: "starter_pack",
    priorityScore: 17.8,
    body: {
      intro: "Vendor management fails quietly — a contract auto-renews, a contact leaves and nobody updates the record, a performance issue goes untracked. This template gives you the structure to prevent that: a single view of every vendor relationship with the information that matters.",
      whatYouGet: [
        "Vendor register: supplier name, category, contract value, renewal date, primary contact, and performance status",
        "Vendor review template: quarterly performance assessment by SLA category",
        "AI prompt to generate a vendor review summary from your performance data",
        "Renewal alert workflow: how to set up automated reminders for contract renewals",
      ],
      whoItsFor: "Ops managers responsible for vendor relationships who want a simple, maintainable vendor register without a complex procurement tool.",
      ctaNote: "Free template. To build a vendor management tool for your ops function, the Torvi Ops track is the guided path.",
    },
  },
];
