import type { PSEOPage } from "../pages";

export const extendedReportingPages: PSEOPage[] = [
  {
    slug: "project-status-report-software",
    title: "Project Status Report Software — Guide | Torvi",
    h1: "Project status report software",
    metaDescription: "A guide to project status report software and AI tools. What to use, what to build, and when each makes sense.",
    keyword: "project status report software",
    cluster: "reporting_automation",
    pageType: "resource_page",
    priorityScore: 28.9,
    body: {
      intro: "Project status reporting software ranges from templates in Notion to purpose-built tools with automated data pulls. The right choice depends on how many projects you run, how frequently you report, and how much customisation your workflow needs. This guide helps you decide.",
      whatYouGet: [
        "Tool comparison: Notion templates, project management integrations, and custom-built reporting tools",
        "When off-the-shelf tools work vs. when a custom build saves more time",
        "AI-assisted reporting workflow: how to generate status reports from project data automatically",
        "Worked example: project reporting system for a consulting firm managing eight concurrent engagements",
      ],
      whoItsFor: "Project managers and consultants who report on multiple projects simultaneously and want a reporting system that is consistent, fast, and low-maintenance.",
      ctaNote: "Free guide. To build your own project status reporting tool, the Torvi Consultant or PM track is the four-week path.",
    },
  },
  {
    slug: "ai-monthly-report-tool",
    title: "AI Monthly Report Tool — Guide | Torvi",
    h1: "AI monthly report tool",
    metaDescription: "How to use AI to generate monthly reports: data extraction, summarisation, and formatting. Guide for ops and PM teams.",
    keyword: "ai monthly report tool",
    cluster: "reporting_automation",
    pageType: "resource_page",
    priorityScore: 23.9,
    body: {
      intro: "Generating monthly reports with AI is now a reliable workflow — provided the inputs are structured and the prompts are designed for the output format you need. This guide covers the exact workflow, from data extraction to final formatting, for ops and PM monthly reports.",
      whatYouGet: [
        "Monthly report AI workflow: data collection → structured input → AI draft → human narrative layer → distribution",
        "Prompt design for monthly reports: how to get executive-quality output from operational data",
        "Data source integration: Google Sheets, Notion, and project management tools as monthly data inputs",
        "Worked example: operations monthly report generated from a Notion database",
      ],
      whoItsFor: "Ops managers and analysts who produce monthly reports and want to reduce the production time from half a day to under two hours.",
      ctaNote: "Free guide. To build an automated monthly reporting tool, the Torvi Ops track gives you the four-week path.",
    },
  },
  {
    slug: "status-report-generator",
    title: "Status Report Generator — AI Guide | Torvi",
    h1: "Status report generator",
    metaDescription: "How to use AI to generate status reports fast: prompts, templates, and integration patterns. Free guide.",
    keyword: "status report generator",
    cluster: "reporting_automation",
    pageType: "resource_page",
    priorityScore: 21.3,
    body: {
      intro: "Status report generation is one of the clearest AI use cases in operations. The data exists, the format is known, the audience is defined — AI handles all three constraints well. This guide covers the workflow that produces a professional status report in under 15 minutes.",
      whatYouGet: [
        "Status report generation workflow: notes and data → AI draft → review and edit → send",
        "Prompt templates for weekly, biweekly, and monthly status reports",
        "Audience calibration: adjusting tone and detail level for engineering, leadership, and clients",
        "Worked example: project status report generated from Jira data and meeting notes",
      ],
      whoItsFor: "Project managers and ops leads who send status reports to multiple audiences and want to eliminate the manual writing work without sacrificing quality.",
      ctaNote: "Free guide. To build a status report generation tool for your team, the Torvi Ops or PM track covers it.",
    },
  },
  {
    slug: "kpi-dashboard-software",
    title: "KPI Dashboard Software — What to Use | Torvi",
    h1: "KPI dashboard software",
    metaDescription: "A guide to KPI dashboard software for ops and leadership teams. What to evaluate and when to build custom.",
    keyword: "kpi dashboard software",
    cluster: "reporting_automation",
    pageType: "resource_page",
    priorityScore: 24.4,
    body: {
      intro: "KPI dashboard software is one of the most competitive categories in operations tooling — and most tools are overkill for what most teams actually need. This guide cuts to the decision: which tool for which context, and when building custom saves more time than configuring off-the-shelf.",
      whatYouGet: [
        "Tool comparison: Notion, Databox, Geckoboard, Looker Studio, and custom builds — what each does well",
        "Configuration cost vs. custom build trade-off: a decision framework",
        "When a simple Notion dashboard beats a dedicated KPI tool",
        "Worked example: ops KPI dashboard built custom in two weeks",
      ],
      whoItsFor: "Ops managers evaluating KPI dashboard options who want a clear recommendation based on their team size, data maturity, and update frequency requirements.",
      ctaNote: "Free guide. To build a custom KPI dashboard for your function, the Torvi Ops track is the four-week path.",
    },
  },
  {
    slug: "business-dashboard-automation",
    title: "Business Dashboard Automation — Guide | Torvi",
    h1: "Business dashboard automation",
    metaDescription: "How to automate your business dashboard: data connections, update scheduling, and alert logic. Guide for ops teams.",
    keyword: "business dashboard automation",
    cluster: "reporting_automation",
    pageType: "resource_page",
    priorityScore: 24.7,
    body: {
      intro: "A business dashboard that requires manual updates is not a dashboard — it is a report that looks like a dashboard. True automation means the data flows in on a schedule, the metrics calculate automatically, and alerts fire when something needs attention. This guide covers how to build that.",
      whatYouGet: [
        "Dashboard automation architecture: data sources → scheduled extraction → metric calculation → visualisation → alert logic",
        "Integration patterns for common business data sources",
        "Alert design: how to define the thresholds that trigger notifications without alert fatigue",
        "Worked example: automated ops dashboard with daily data refresh",
      ],
      whoItsFor: "Ops managers and analysts who maintain business dashboards and want to replace manual data entry with automated data flows.",
      ctaNote: "Free guide. To build a fully automated business dashboard, the Torvi Ops track gives you the guided four-week path.",
    },
  },
  {
    slug: "operations-report-generator",
    title: "Operations Report Generator — AI Guide | Torvi",
    h1: "Operations report generator",
    metaDescription: "How to use AI to generate operations reports: workflow, prompts, and integration. Guide for ops managers.",
    keyword: "operations report generator",
    cluster: "reporting_automation",
    pageType: "resource_page",
    priorityScore: 18.4,
    body: {
      intro: "Operations reports are the most automatable documents in any function — they follow a known structure, pull from known data sources, and go to a known audience on a known schedule. Building a generator that handles all of that is a two-to-three week project. This guide shows you how.",
      whatYouGet: [
        "Ops report generator workflow: structured data input → AI draft generation → review → distribution",
        "Prompt design for different ops report types: weekly ops review, monthly summary, and quarterly business review",
        "Data integration: how to pull from your ops tools into the generation workflow",
        "Worked example: automated weekly ops report for a BizOps team",
      ],
      whoItsFor: "Ops managers who produce regular operations reports and want to automate the data collection and drafting without losing the analytical quality.",
      ctaNote: "Free guide. To build your ops report generator, the Torvi Ops track is the four-week path.",
    },
  },
  {
    slug: "reporting-automation-tools",
    title: "Reporting Automation Tools — Guide | Torvi",
    h1: "Reporting automation tools",
    metaDescription: "A guide to reporting automation tools for ops and PM teams. What to evaluate, configure, and build.",
    keyword: "reporting automation tools",
    cluster: "reporting_automation",
    pageType: "resource_page",
    priorityScore: 14.8,
    body: {
      intro: "Reporting automation tools have proliferated — but most of them solve a narrow version of the problem. They automate the data pull but not the narrative, or they handle the formatting but not the distribution. This guide helps you find the tool that covers your specific reporting gap.",
      whatYouGet: [
        "Reporting automation tool categories: BI platforms, workflow automation, AI-native generators, and custom builds",
        "Gap analysis: which part of your reporting workflow is the bottleneck",
        "Tool recommendations by reporting type: weekly status, monthly ops, client reporting, and KPI dashboards",
        "When to build custom: the signals that indicate an off-the-shelf tool will not cut it",
      ],
      whoItsFor: "Ops managers and analysts evaluating reporting automation options who want a clear framework for selecting the right tool for their specific workflow.",
      ctaNote: "Free guide. To build a custom reporting tool for your function, the Torvi Ops track is the path.",
    },
  },
];
