import type { PSEOPage } from "../pages";

export const extendedPmPages: PSEOPage[] = [
  {
    slug: "product-management-ai-tools",
    title: "AI Tools for Product Management — Practical Guide | Torvi",
    h1: "Product management AI tools",
    metaDescription: "The practical PM's guide to AI tools: what to use for discovery, planning, writing, and analysis — and what to build custom.",
    keyword: "product management ai tools",
    cluster: "pm_ai_tools",
    pageType: "resource_page",
    priorityScore: 31.9,
    body: {
      intro: "Product managers have more AI tools available than any other function — and the lowest signal-to-noise ratio in evaluating them. This guide cuts to what actually works: the tools worth using by use case, and a clear decision point for when to build something custom instead.",
      whatYouGet: [
        "AI tool map by PM use case: discovery, requirements, roadmap, stakeholder comms, release notes, and analysis",
        "Which tasks AI handles well (summarisation, structure, formatting) vs. poorly (strategy, trade-offs, judgment)",
        "Buy vs. build guide for PM tooling: when a custom tool pays off",
        "The five PM workflows with the highest AI leverage in 2024–2025",
      ],
      whoItsFor: "Product managers who use AI tools regularly and want a structured view of how to deploy them across their workflow — not just for one-off prompting.",
      ctaNote: "Free guide. To build a custom PM tool that automates your specific workflow, the Torvi PM track is the four-week path.",
    },
  },
  {
    slug: "ai-for-product-management",
    title: "AI for Product Management — What Actually Works | Torvi",
    h1: "AI for product management",
    metaDescription: "A practical guide to using AI in product management: discovery, PRDs, roadmaps, release notes, and stakeholder comms.",
    keyword: "ai for product management",
    cluster: "pm_ai_tools",
    pageType: "resource_page",
    priorityScore: 26.0,
    body: {
      intro: "AI for product management is most valuable when it handles the structured, repeatable work — and stays out of the strategic, judgment-heavy decisions. This guide shows you exactly where that line is and how to build workflows that put AI in the right role.",
      whatYouGet: [
        "AI in the PM workflow: where it accelerates (PRDs, updates, notes, summaries) vs. where it does not (strategy, prioritisation, stakeholder trust)",
        "Prompt patterns for core PM outputs: requirements, release notes, stakeholder updates, user research synthesis",
        "A PM AI workflow design guide: how to build habits that compound",
        "Worked examples for three PM archetypes: feature PM, platform PM, and growth PM",
      ],
      whoItsFor: "Product managers at any stage of AI adoption who want a clear, honest guide to what AI can and cannot do for their role.",
      ctaNote: "Free guide. To go beyond prompting and build a tool your team uses daily, the Torvi PM track is the guided path.",
    },
  },
  {
    slug: "roadmap-automation-tool",
    title: "Roadmap Automation — Guide for Product Managers | Torvi",
    h1: "Roadmap automation",
    metaDescription: "How PMs use AI to automate roadmap updates, prioritisation summaries, and stakeholder presentations. Guide and templates.",
    keyword: "roadmap automation tool",
    cluster: "pm_ai_tools",
    pageType: "resource_page",
    priorityScore: 22.9,
    body: {
      intro: "Roadmap automation is not about removing PM judgment from prioritisation — it is about removing the manual work of formatting, updating, and communicating the roadmap. These are the tasks AI handles well, and they currently take hours every sprint.",
      whatYouGet: [
        "Roadmap update automation: AI-assisted changelog generation from tickets and release notes",
        "Stakeholder roadmap summary: AI prompt to generate audience-appropriate roadmap views",
        "Prioritisation scoring: using AI to apply and document scoring frameworks consistently",
        "Worked example: weekly roadmap update workflow from Jira to stakeholder email",
      ],
      whoItsFor: "Product managers who spend significant time keeping their roadmap documentation and stakeholder communications current and want to automate the formatting work.",
      ctaNote: "Free guide. To build a roadmap automation tool for your team, the Torvi PM track walks you through it.",
    },
  },
  {
    slug: "chatgpt-prompts-for-product-strategy",
    title: "ChatGPT Prompts for Product Strategy — Free | Torvi",
    h1: "ChatGPT prompts for product strategy",
    metaDescription: "ChatGPT prompts for product strategy: market analysis, opportunity framing, positioning, and strategic narrative. Free.",
    keyword: "chatgpt prompts for product strategy",
    cluster: "pm_ai_tools",
    pageType: "resource_page",
    priorityScore: 21.4,
    body: {
      intro: "AI is not going to replace product strategy — but it can accelerate the research, framing, and documentation that good strategy requires. These prompts are for the analytical and communication work: market sizing, opportunity framing, competitive positioning, and strategic narrative.",
      whatYouGet: [
        "5 strategy prompts: market opportunity framing, competitive positioning, strategic narrative draft, investment case summary, and strategic review facilitation guide",
        "Context-feeding guide: what to give the AI to get strategy-quality output",
        "Prompts for stress-testing a strategy: challenger assumptions, risk identification, and what-if scenarios",
        "Worked example: product strategy one-pager generated from market notes",
      ],
      whoItsFor: "Product managers and product leaders who want to use AI to accelerate strategy work without outsourcing the thinking.",
      ctaNote: "Free prompts. To build a strategy documentation tool for your product team, the Torvi PM track covers it.",
    },
  },
  {
    slug: "product-discovery-automation-tool",
    title: "Product Discovery Automation — Guide | Torvi",
    h1: "Product discovery automation",
    metaDescription: "How to automate parts of product discovery: research synthesis, interview analysis, and insight generation. Guide for PMs.",
    keyword: "product discovery automation tool",
    cluster: "pm_ai_tools",
    pageType: "resource_page",
    priorityScore: 26.0,
    body: {
      intro: "Product discovery has a high-value automation opportunity: the synthesis layer. Running interviews, mapping themes, extracting insights, and writing summaries are all tasks AI handles well when given structured prompts and clean inputs. This guide covers how to automate that layer.",
      whatYouGet: [
        "Discovery synthesis workflow: interviews → transcripts → AI theme extraction → insight summary → recommendation",
        "AI prompts for: interview synthesis, theme mapping, insight extraction, and opportunity framing",
        "Research repository integration: how to store and retrieve synthesised insights systematically",
        "Worked example: customer research synthesis for a B2B workflow tool",
      ],
      whoItsFor: "Product managers who run regular discovery research and want to reduce the time between interviews and actionable insights.",
      ctaNote: "Free guide. To build a research synthesis tool for your team, the Torvi PM track is the guided path.",
    },
  },
  {
    slug: "backlog-template-for-product-managers",
    title: "Backlog Template for Product Managers — Free | Torvi",
    h1: "Backlog template for product managers",
    metaDescription: "A structured product backlog template for PMs. Story, priority, effort estimate, acceptance criteria, and status. Free.",
    keyword: "backlog template for product managers",
    cluster: "pm_ai_tools",
    pageType: "starter_pack",
    priorityScore: 10.8,
    body: {
      intro: "A well-structured backlog is the difference between a sprint that runs smoothly and one that starts with a 45-minute refinement session. This template gives you the format that engineers can pick up and work from without a follow-up conversation.",
      whatYouGet: [
        "Backlog item structure: user story, acceptance criteria, effort estimate, priority score, dependencies, and status",
        "Priority scoring guide: a lightweight framework for consistent prioritisation",
        "AI prompt to generate backlog items from a feature description or user interview",
        "Sprint planning preparation checklist: how to review your backlog before refinement",
      ],
      whoItsFor: "Product managers who manage a backlog in Jira, Linear, or Notion and want a consistent item format that reduces refinement time.",
      ctaNote: "Free template. To build a backlog management tool for your team, the Torvi PM track is the path.",
    },
  },
  {
    slug: "prd-template-for-product-managers",
    title: "PRD Template for Product Managers — Free | Torvi",
    h1: "PRD template for product managers",
    metaDescription: "A PRD template built for product managers: context, problem, requirements, and success criteria. Fast to write, clear to read. Free.",
    keyword: "prd template for product managers",
    cluster: "pm_ai_tools",
    pageType: "template_page",
    priorityScore: 17.0,
    body: {
      intro: "The best PRD is the one engineering actually reads. That means it is short, structured, and specific — not a 15-page doc that explains the history of the problem before stating the requirement. This template is built around what engineering needs, not what PRDs traditionally look like.",
      whatYouGet: [
        "PM-optimised PRD: problem context, user need, requirements (functional and non-functional), non-requirements, open questions, and success metric",
        "AI prompt to generate a PRD first draft from discovery notes",
        "Review checklist: questions to ask before sharing with engineering",
        "Worked example for a PM-built internal tool",
      ],
      whoItsFor: "Product managers who write PRDs for engineering teams and want a format that is fast to produce and immediately actionable to receive.",
      ctaNote: "Free template. To build a PRD generation tool your team uses in their workflow, the Torvi PM track covers it.",
    },
  },
  {
    slug: "roadmap-template-for-product-managers",
    title: "Roadmap Template for Product Managers — Free | Torvi",
    h1: "Roadmap template for product managers",
    metaDescription: "A practical roadmap template for PMs: now, next, later format with outcomes and milestones. Free download.",
    keyword: "roadmap template for product managers",
    cluster: "pm_ai_tools",
    pageType: "guide_page",
    priorityScore: 11.5,
    body: {
      intro: "Roadmaps fail when they are either too detailed (a release plan masquerading as a roadmap) or too vague (a list of themes with no commitment). This template uses the now/next/later format with outcome anchors — communicating direction without committing to dates you cannot keep.",
      whatYouGet: [
        "Roadmap format: now/next/later columns with outcome statements, key milestones, and dependencies",
        "Audience variants: engineering detail view vs. leadership summary vs. customer-facing roadmap",
        "AI prompt to generate a roadmap draft from your strategy doc and backlog",
        "Quarterly roadmap review process guide",
      ],
      whoItsFor: "Product managers who maintain a roadmap for multiple audiences and want a format that is honest about uncertainty without being unhelpfully vague.",
      ctaNote: "Free template. To build a roadmap communication tool for your team, the Torvi PM track is the guided path.",
    },
  },
  {
    slug: "product-discovery-template",
    title: "Product Discovery Template — Free | Torvi",
    h1: "Product discovery template for product managers",
    metaDescription: "A product discovery template covering problem framing, user research plan, synthesis, and recommendation. Free download.",
    keyword: "product discovery template for product managers",
    cluster: "pm_ai_tools",
    pageType: "template_page",
    priorityScore: 16.9,
    body: {
      intro: "Product discovery without structure is just interviews and opinions. This template gives you the structure: a clear problem frame, a research plan that answers the right questions, a synthesis process, and a recommendation that engineering and leadership can act on.",
      whatYouGet: [
        "Discovery template: problem hypothesis, research questions, method selection, synthesis format, and go/no-go recommendation",
        "Interview guide template: the questions that surface real user behaviour, not stated preferences",
        "AI prompt to synthesise discovery findings into a structured summary",
        "Worked example: discovery phase for an internal workflow tool",
      ],
      whoItsFor: "Product managers who run discovery for new features or tools and want a consistent, structured process from problem framing to recommendation.",
      ctaNote: "Free template. To build a discovery and synthesis tool for your team, the Torvi PM track covers it.",
    },
  },
];
