import type { PSEOPage } from "../pages";

export const extendedVibeCodingPages: PSEOPage[] = [
  {
    slug: "ai-coding-training-for-operations-manager",
    title: "AI Coding Training for Operations Managers — Torvi",
    h1: "AI coding training for operations managers",
    metaDescription: "Structured AI coding training for ops managers. Build and ship a workflow automation tool in 4 weeks. Open enrolment.",
    keyword: "ai coding training for operations manager",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 22.0,
    body: {
      intro: "Operations managers have the clearest case for building AI tools: you know exactly which manual workflows are slowing your team down, you have direct access to the stakeholders, and you do not need to convince anyone of the value. Torvi gives you the four-week path to build and ship the automation yourself.",
      whatYouGet: [
        "Week 0: Tool brief — scope your automation to something shippable in four weeks",
        "Weeks 1–4: Ops-specific build path covering intake, routing, reporting, and workflow automation",
        "Weekly office hours with practitioners who have built and deployed ops tools",
        "A working, deployed tool at the end — not a demo",
      ],
      whoItsFor: "Operations managers who know which workflow they want to automate and want a structured, supported path to build it themselves without hiring a developer.",
      ctaNote: "Open enrolment, start immediately. Founding rate €200.",
    },
  },
  {
    slug: "ai-coding-course-for-managers",
    title: "AI Coding Course for Managers — Torvi",
    h1: "AI coding course for managers",
    metaDescription: "A 4-week AI coding programme for managers who want to ship one work tool. Guided, practical, no development background required.",
    keyword: "ai coding course for managers",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 21.7,
    body: {
      intro: "Managers who can build tools have a different relationship with their work than those who cannot. Torvi is not a course in the traditional sense — it is a four-week guided build where the output is a working tool you use with your team, not a certificate from completing modules.",
      whatYouGet: [
        "A structured build path designed for managers without a development background",
        "Weekly office hours for real-time unblocking — the hardest part of building without a team",
        "AI-native tooling: Cursor, prompt engineering, and lightweight deployment",
        "A shipped tool at the end that solves a real management workflow problem",
      ],
      whoItsFor: "Managers at any level who want to develop the ability to build tools — to reduce their dependence on engineering, move faster, and solve workflow problems themselves.",
      ctaNote: "Open enrolment. Founding rate €200. Start when you are ready.",
    },
  },
  {
    slug: "ai-coding-course-online",
    title: "AI Coding Course Online — Build a Real Tool | Torvi",
    h1: "AI coding course online",
    metaDescription: "An online AI coding programme for senior professionals. Build and ship a work tool in 4 weeks. Open enrolment, start immediately.",
    keyword: "ai coding course online",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 20.3,
    body: {
      intro: "Most online AI coding courses end with a demo project. Torvi ends with a tool you actually use — built around your specific work problem, deployed in your actual workflow. The difference is the structure: weekly guided builds, office hours support, and a real deliverable.",
      whatYouGet: [
        "Fully online, self-paced build path with weekly guided checkpoints",
        "Weekly office hours (live) for unblocking when you get stuck",
        "Built around your role: PM, Ops, or Consultant track with specific guidance for each",
        "A shipped, working tool at the end — the kind you can show at work",
      ],
      whoItsFor: "Senior professionals anywhere in the world who want to learn AI-native tool building through a structured, outcome-focused programme rather than a course library.",
      ctaNote: "Open enrolment, fully online, start immediately. Founding rate €200.",
    },
  },
  {
    slug: "vibe-coding-program-online",
    title: "Vibe Coding Programme — Online | Torvi",
    h1: "Vibe coding programme online",
    metaDescription: "An online vibe coding programme for senior professionals. Ship one work tool in 4 weeks. Guided, practical, open enrolment.",
    keyword: "vibe coding program online",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 21.8,
    body: {
      intro: "Vibe coding is the practice of building software through natural language — describing what you want to a capable AI and iterating until it works. Torvi structures that practice into a four-week build programme: clear problem, guided process, real output.",
      whatYouGet: [
        "Structured vibe coding curriculum: prompt engineering, iteration patterns, and deployment for non-developers",
        "Role-specific guidance for PM, Ops, and Consultant archetypes",
        "Weekly live office hours for support when the iteration stalls",
        "A shipped tool — the vibe coding proof of concept that actually matters",
      ],
      whoItsFor: "Senior professionals who want to learn vibe coding in a structured, outcome-focused way — not by watching tutorials, but by building something real.",
      ctaNote: "Open enrolment, start immediately. €200 founding rate.",
    },
  },
  {
    slug: "ai-coding-training-for-consultants",
    title: "AI Coding Training for Consultants — Torvi",
    h1: "AI coding training for consultants",
    metaDescription: "A 4-week guided build for consultants who want to ship a client-facing or internal AI tool. Open enrolment, start immediately.",
    keyword: "ai coding training for consultants",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 18.9,
    body: {
      intro: "Consultants who can build tools for their clients have a differentiated practice. Torvi gives you the structured path to develop that capability — starting with a tool that solves a real problem in your consulting work and building from there.",
      whatYouGet: [
        "Consultant-specific build path: client diagnostics, reporting tools, delivery trackers, and intake automation",
        "Week 0: scope the tool that makes the most sense for your practice right now",
        "Weekly office hours with practitioners who have built and deployed consulting tools",
        "A shipped tool you can demo to clients or deploy in your next engagement",
      ],
      whoItsFor: "Independent consultants and fractional executives who want to add tool-building capability to their practice — to differentiate, to deliver faster, and to build IP.",
      ctaNote: "Open enrolment, start immediately. Founding rate €200.",
    },
  },
  {
    slug: "ai-coding-bootcamp-for-ops-manager",
    title: "AI Coding Bootcamp for Ops Managers — Torvi",
    h1: "AI coding bootcamp for ops managers",
    metaDescription: "A focused 4-week AI tool building programme for operations managers. Ship one automation tool. Open enrolment.",
    keyword: "ai coding bootcamp for ops manager",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 24.9,
    body: {
      intro: "Operations managers who build their own automation tools do not wait in the engineering queue. Torvi is the four-week programme that gets you there — a focused build with weekly guidance, office hours support, and a deployed tool at the end.",
      whatYouGet: [
        "Ops-specific build path: intake tools, routing logic, reporting automation, and workflow tools",
        "Structured week-by-week delivery: brief → core logic → interface → ship",
        "Weekly office hours for real-time unblocking",
        "A deployed, working automation tool your team uses",
      ],
      whoItsFor: "Operations managers with a specific automation in mind who want the structure and support to build it themselves in four weeks.",
      ctaNote: "Open enrolment. Start immediately. Founding rate €200.",
    },
  },
  {
    slug: "ai-coding-workshop-for-product-manager",
    title: "AI Coding Workshop for Product Managers — Torvi",
    h1: "AI coding workshop for product managers",
    metaDescription: "A hands-on AI coding programme for product managers. Build and ship one PM tool in 4 weeks. Open enrolment.",
    keyword: "ai coding workshop for product manager",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 25.5,
    body: {
      intro: "Product managers who have built a tool think about product differently. They understand implementation constraints from experience, not theory. Torvi gives you that experience — in a structured four-week build programme designed for the PM role.",
      whatYouGet: [
        "PM-specific build path: PRD generators, meeting notes tools, stakeholder update automation, release notes tools",
        "Hands-on weekly structure: define, build, test, ship — one week at a time",
        "Weekly office hours to unblock and review your build",
        "A working PM tool you use in your actual workflow",
      ],
      whoItsFor: "Product managers who want to develop hands-on AI tool building capability — to be more credible with engineering, more independent, and more effective.",
      ctaNote: "Open enrolment, start immediately. €200 founding rate.",
    },
  },
  {
    slug: "ai-coding-training-for-pm",
    title: "AI Coding Training for PMs — Torvi",
    h1: "AI coding training for PM",
    metaDescription: "AI coding training designed for product managers. Ship one tool in 4 weeks. Structured, practical, outcome-first.",
    keyword: "ai coding training for pm",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 25.0,
    body: {
      intro: "AI coding training for PMs means learning by building, not by watching. Torvi structures the build around the PM role: you start with a problem from your actual work, build the tool that solves it, and ship it in four weeks with weekly guidance and office hours support.",
      whatYouGet: [
        "PM-tailored build curriculum: prompt engineering, lightweight UI, data integration, and deployment",
        "Week 0 tool brief: define your build scope before you start writing any code",
        "Weekly office hours with practitioners who have shipped PM tools",
        "One shipped tool at the end — your proof of capability",
      ],
      whoItsFor: "Product managers at any stage who want to develop AI tool building capability through a structured, supported four-week programme rather than self-directed learning.",
      ctaNote: "Open enrolment. Start when you are ready. €200 founding rate.",
    },
  },
  {
    slug: "vibe-coding-workshop-online",
    title: "Vibe Coding Workshop — Online | Torvi",
    h1: "Vibe coding workshop online",
    metaDescription: "An online vibe coding workshop for senior professionals. 4-week guided build, weekly office hours, one shipped tool. Start now.",
    keyword: "vibe coding workshop online",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 17.2,
    body: {
      intro: "Vibe coding workshops tend to end with a tutorial project. Torvi ends with a tool you actually use. The difference is the four-week structure, the role-specific guidance, and the office hours that keep you moving when you get stuck.",
      whatYouGet: [
        "Four-week online build programme with weekly structure and live office hours",
        "Role track selection: PM, Ops, or Consultant — each with specific guidance",
        "AI-native tooling: Cursor, prompt engineering, and deployment",
        "A shipped tool — built around your specific work problem",
      ],
      whoItsFor: "Senior professionals who want to develop vibe coding capability in a structured programme — not a YouTube series they start and abandon.",
      ctaNote: "Open enrolment, fully online. €200 founding rate.",
    },
  },
];
