import type { PSEOPage } from "../pages";

export const internalToolsPages: PSEOPage[] = [
  {
    slug: "build-internal-tools-with-ai",
    title: "Build Internal Tools with AI — Guide | Torvi",
    h1: "Build internal tools with AI",
    metaDescription: "How to build internal tools with AI: scoping, prompting, interfaces, and deployment. A practical guide for non-developers.",
    keyword: "build internal tools with ai",
    cluster: "internal_tools",
    pageType: "resource_page",
    priorityScore: 27.5,
    body: {
      intro: "Building internal tools with AI is now genuinely accessible to non-developers — but only if you understand what AI is good at (generating logic, writing code, suggesting structure) vs. what still requires human judgment (scoping, user testing, deployment decisions). This guide covers the full process.",
      whatYouGet: [
        "The four-step internal tool build: define the problem, design the logic, build with AI assistance, deploy and iterate",
        "AI tooling guide: Cursor, Claude, and no-code/low-code options — when to use each",
        "Scope control: how to define an internal tool that can be shipped in two weeks, not six months",
        "Worked example: ops intake tool built by a non-developer PM in three weeks",
      ],
      whoItsFor: "Senior professionals who have a tool idea and want to build it themselves using AI assistance — without hiring a developer or learning to code from scratch.",
      ctaNote: "Free guide. The Torvi run gives you a structured four-week path to ship your internal tool with weekly guidance and office hours support.",
    },
  },
  {
    slug: "internal-dashboard-platform",
    title: "Internal Dashboard — How to Build One | Torvi",
    h1: "Internal dashboard platform",
    metaDescription: "How to build an internal dashboard: data sources, metrics selection, and deployment options. Guide for ops and PM teams.",
    keyword: "internal dashboard platform",
    cluster: "internal_tools",
    pageType: "resource_page",
    priorityScore: 32.0,
    body: {
      intro: "Internal dashboards fail for two reasons: they try to show everything, or they are built once and never maintained. This guide covers how to build a dashboard with the right scope — five to seven metrics that matter — connected to real data, and designed to stay relevant.",
      whatYouGet: [
        "Dashboard scoping guide: how to select the metrics that drive decisions vs. the ones that just fill space",
        "Data source connection options: Google Sheets, Notion, Airtable, and lightweight database connections",
        "Build approach comparison: no-code (Retool, Glide), low-code, and AI-assisted custom builds",
        "Maintenance and update design: how to build a dashboard that stays current without manual intervention",
      ],
      whoItsFor: "Ops managers and team leads who need an internal dashboard for their function and want to build it themselves rather than wait for an engineering sprint.",
      ctaNote: "Free guide. The Torvi Ops track gives you the guided four-week path to build and ship your dashboard.",
    },
  },
  {
    slug: "internal-reporting-tool-platform",
    title: "Internal Reporting Tool — Build Guide | Torvi",
    h1: "Internal reporting tool platform",
    metaDescription: "How to build an internal reporting tool that generates consistent, automated reports for your team. Guide and templates.",
    keyword: "internal reporting tool platform",
    cluster: "internal_tools",
    pageType: "resource_page",
    priorityScore: 33.0,
    body: {
      intro: "An internal reporting tool that actually runs is better than a reporting process that depends on someone remembering to do it. Building a tool that pulls data, formats a report, and sends it on schedule is now achievable without engineering support. This guide shows you how.",
      whatYouGet: [
        "Internal reporting tool architecture: data source → extraction → AI summarisation → formatting → distribution",
        "Stack options by complexity: simple (Google Sheets + ChatGPT), medium (Notion + Make), advanced (custom build with Cursor)",
        "Report design guide: what information to include, how to structure it for different audiences",
        "Worked example: weekly ops report tool built and deployed in four weeks",
      ],
      whoItsFor: "Ops managers and PMs who produce the same report type week after week and want to build a tool that generates it automatically.",
      ctaNote: "Free guide. The Torvi Ops or PM track gives you the structured path to ship your reporting tool in four weeks.",
    },
  },
  {
    slug: "build-internal-tools",
    title: "Build Internal Tools — The Practical Guide | Torvi",
    h1: "Build internal tools",
    metaDescription: "A practical guide to building internal tools: scope, stack, build process, and deployment. For non-developers who want to ship.",
    keyword: "build internal tools",
    cluster: "internal_tools",
    pageType: "solution_page",
    priorityScore: 32.7,
    body: {
      intro: "Internal tools are the most underbuilt category of software. Every team has three or four manual workflows that a simple tool would fix — but they never get built because they are not a priority for engineering. Building them yourself is now the realistic option.",
      whatYouGet: [
        "Internal tool build process: scope the problem → design the logic → build with AI assistance → test → deploy",
        "Stack selection guide: when to use no-code, low-code, or AI-assisted custom code",
        "The most buildable internal tools for PMs, ops leads, and consultants",
        "A four-week build schedule that gets you from idea to deployed tool",
      ],
      whoItsFor: "Senior professionals with a tool idea who want to build it themselves — without a development background and without waiting for an engineering sprint.",
      ctaNote: "The Torvi run gives you the four-week guided path: weekly structure, an AI coach, and office hours when you get stuck. Open enrolment, €200.",
    },
  },
  {
    slug: "internal-tools-for-startups",
    title: "Internal Tools for Startups — Build Guide | Torvi",
    h1: "Internal tools for startups",
    metaDescription: "How startups build internal tools fast: scope, stack, and deployment. Guide for founders and ops leads.",
    keyword: "internal tools for startups",
    cluster: "internal_tools",
    pageType: "resource_page",
    priorityScore: 22.2,
    body: {
      intro: "Startups run on manual processes longer than they should — because internal tools feel like a luxury when you are still finding product-market fit. But the right internal tool at the right moment is a competitive advantage, not a distraction. This guide covers which tools to build first and how to build them fast.",
      whatYouGet: [
        "Priority matrix for startup internal tools: which workflows to automate first based on team size and growth stage",
        "Build speed guide: how to get an internal tool from idea to deployed in two weeks",
        "Stack comparison for startup tooling: no-code vs. low-code vs. AI-assisted custom builds",
        "Worked example: Series A startup ops lead builds intake routing tool in three weeks",
      ],
      whoItsFor: "Founders, ops leads, and Chiefs of Staff at early-stage companies who want to automate internal workflows without a dedicated engineering resource.",
      ctaNote: "Free guide. The Torvi run gives you the guided four-week path to ship your startup's internal tool.",
    },
  },
  {
    slug: "internal-app-for-startups",
    title: "Build an Internal App for Your Startup | Torvi",
    h1: "Internal app for startups",
    metaDescription: "How to build an internal app for your startup team: scoping, building, and deploying without a developer. Guide.",
    keyword: "internal app for startups",
    cluster: "internal_tools",
    pageType: "solution_page",
    priorityScore: 23.8,
    body: {
      intro: "Most startup internal apps do not need a developer — they need a clear scope, the right stack, and two or three focused weeks. AI tools have changed what is buildable by a non-developer, and the ceiling is higher than most people think.",
      whatYouGet: [
        "Startup internal app archetypes: intake tool, reporting dashboard, onboarding workflow, and data viewer — scoped for a non-developer build",
        "Stack selection guide: Retool, Glide, Bubble, and AI-assisted code for different app types",
        "One-week MVP build plan: the minimum viable app you can ship and iterate from",
        "Worked example: startup ops lead builds a client onboarding app in three weeks",
      ],
      whoItsFor: "Founders, ops leads, and senior team members at early-stage startups who want to build internal apps for their team without hiring a developer.",
      ctaNote: "Free guide. The Torvi run gives you the guided path from app brief to deployed product in four weeks.",
    },
  },
  {
    slug: "internal-app-template",
    title: "Internal App Template — Free Download | Torvi",
    h1: "Internal app template",
    metaDescription: "A free internal app template covering spec, data model, user flow, and deployment plan. Built for non-developers.",
    keyword: "internal app template",
    cluster: "internal_tools",
    pageType: "template_page",
    priorityScore: 22.6,
    body: {
      intro: "Building an internal app without a spec is how you end up rebuilding it three times. This template gives you the minimum viable spec: what the app does, who uses it, what data it handles, and how it fits into your existing workflow.",
      whatYouGet: [
        "Internal app spec: purpose statement, user definition, data model, user flow, integration requirements, and success metric",
        "AI prompt to generate a spec from a description of the current manual workflow",
        "Stack selection guide based on your spec",
        "Worked example: project intake app spec for an ops team",
      ],
      whoItsFor: "Ops managers, PMs, and senior professionals who want to build an internal app and need a structured spec before they start.",
      ctaNote: "Free template. The Torvi run turns your spec into a shipped app in four weeks.",
    },
  },
  {
    slug: "workflow-tool-for-teams",
    title: "Workflow Tool for Teams — Build Guide | Torvi",
    h1: "Workflow tool for teams",
    metaDescription: "How to build a workflow tool for your team: process automation, routing, and reporting in one tool. Guide and templates.",
    keyword: "workflow tool for teams",
    cluster: "internal_tools",
    pageType: "resource_page",
    priorityScore: 23.4,
    body: {
      intro: "A workflow tool built for your team's specific process is more valuable than a general-purpose automation tool configured to approximate it. The gap between 'configured off-the-shelf' and 'built for us' is where team productivity lives. This guide covers how to build yours.",
      whatYouGet: [
        "Workflow tool architecture: intake, routing, processing, notification, and reporting layers",
        "Scope guide: how to scope a workflow tool that can be shipped in four weeks",
        "Build options: no-code, low-code, and AI-assisted custom — with worked examples for each",
        "Team adoption guide: how to get your team using the tool from week one",
      ],
      whoItsFor: "Team leads and ops managers who have a specific workflow that off-the-shelf tools do not quite fit and want to build something custom.",
      ctaNote: "Free guide. The Torvi run gives you the four-week guided path to ship your workflow tool.",
    },
  },
  {
    slug: "operations-dashboard-for-teams",
    title: "Operations Dashboard for Teams — Build Guide | Torvi",
    h1: "Operations dashboard for teams",
    metaDescription: "How to build an operations dashboard for your team: metrics, data sources, and deployment. Guide for ops managers.",
    keyword: "operations dashboard for teams",
    cluster: "internal_tools",
    pageType: "solution_page",
    priorityScore: 21.7,
    body: {
      intro: "An operations dashboard that your team actually uses has two properties: it shows the metrics that drive decisions, and it updates without manual effort. Building one that does both is the Torvi Ops track's Week 3 deliverable for most participants.",
      whatYouGet: [
        "Ops dashboard design guide: metric selection, data source mapping, and update frequency",
        "Build approach by data maturity: from Notion database to custom dashboard",
        "Visualisation guide: which chart types for which metric types",
        "Worked example: ops team dashboard built in three weeks",
      ],
      whoItsFor: "Operations managers who want a team dashboard that shows the metrics that matter — updated automatically, without a data team.",
      ctaNote: "Free guide. The Torvi Ops track gives you the guided path to ship your ops dashboard.",
    },
  },
];
