import type { PSEOPage } from "../pages";

export const meetingsActionItemsPages: PSEOPage[] = [
  {
    slug: "meeting-agenda-template",
    title: "Meeting Agenda Template — Free Download | Torvi",
    h1: "Meeting agenda template",
    metaDescription: "A practical meeting agenda template that produces actionable meetings. Covers objective, timebox, owners, and pre-read. Free.",
    keyword: "meeting agenda template",
    cluster: "meetings_and_action_items",
    pageType: "starter_pack",
    priorityScore: 41.8,
    body: {
      intro: "Most meeting agendas are lists of topics. This template forces something different: every agenda item has an objective, an owner, a timebox, and a decision or output. Meetings run to time. Outcomes are clear before anyone leaves the room.",
      whatYouGet: [
        "Meeting agenda structure: objective statement, pre-read link, agenda items with owner + timebox + output, decisions log, and actions",
        "Variants for recurring team meetings, project reviews, stakeholder check-ins, and retrospectives",
        "AI prompt to generate an agenda from a meeting purpose statement",
        "Worked example for a weekly ops review",
      ],
      whoItsFor: "Team leads and project managers who run recurring meetings and want to stop wasting 30 minutes at the end asking what was decided and who is doing what.",
      ctaNote: "Free template. If you want to build an AI meeting tool that generates agendas and captures action items automatically, the Torvi Ops track covers it.",
    },
  },
  {
    slug: "action-items-template",
    title: "Action Items Template — Free Download | Torvi",
    h1: "Action items template",
    metaDescription: "A clean action items template for meetings and projects. Owner, due date, status, and context fields. Free download.",
    keyword: "action items template",
    cluster: "meetings_and_action_items",
    pageType: "starter_pack",
    priorityScore: 26.4,
    body: {
      intro: "An action item without an owner is a wish. This template enforces the basics — every action has an owner, a due date, a clear verb, and a context note. Nothing ambiguous, nothing incomplete.",
      whatYouGet: [
        "Action items table format: action, owner, due date, status, and context",
        "AI prompt to extract action items from a meeting transcript or notes",
        "Weekly review format: open items, completed, and blockers",
        "Worked example from a project review meeting",
      ],
      whoItsFor: "Team leads and project managers who track action items across multiple meetings and want a consistent format that makes follow-through impossible to avoid.",
      ctaNote: "Free template. To build an action item tracking tool that pulls from your meetings automatically, the Torvi Ops track is how.",
    },
  },
  {
    slug: "meeting-minutes-template",
    title: "Meeting Minutes Template — Free Download | Torvi",
    h1: "Meeting minutes template",
    metaDescription: "A professional meeting minutes template with AI prompt for first-draft generation. Covers decisions, actions, and attendees. Free.",
    keyword: "meeting minutes template",
    cluster: "meetings_and_action_items",
    pageType: "template_page",
    priorityScore: 25.6,
    body: {
      intro: "Meeting minutes exist for one reason: so people who were not in the room know what happened, and people who were in the room remember what they agreed to. This template covers both — clean enough to send immediately after the meeting, complete enough to be the record.",
      whatYouGet: [
        "Meeting minutes structure: date, attendees, objective, decisions, action items, next meeting",
        "AI prompt to generate minutes from a recording transcript",
        "Formal and informal variants (board minutes vs. team meeting notes)",
        "Worked example for a steering committee meeting",
      ],
      whoItsFor: "Chiefs of Staff, project managers, and executive assistants who take minutes regularly and want a consistent, professional format they can produce in under 10 minutes.",
      ctaNote: "Free template. To build an automated meeting minutes tool that generates these from recordings, the Torvi Ops track covers it.",
    },
  },
  {
    slug: "meeting-notes-template",
    title: "Meeting Notes Template — Free Download | Torvi",
    h1: "Meeting notes template",
    metaDescription: "A simple, structured meeting notes template. Decisions, action items, context. Ready to send in 5 minutes. Free.",
    keyword: "meeting notes template",
    cluster: "meetings_and_action_items",
    pageType: "starter_pack",
    priorityScore: 23.0,
    body: {
      intro: "Good meeting notes take five minutes to write and prevent five follow-up emails. This template gives you a structure that is fast enough to fill in during the meeting and clear enough to send immediately after.",
      whatYouGet: [
        "Three-section format: what was discussed, what was decided, what happens next",
        "AI prompt to tidy and structure rough notes taken during a meeting",
        "Variants for 1:1s, team meetings, and client calls",
        "Worked example from a product review meeting",
      ],
      whoItsFor: "Anyone who takes notes in meetings and wants a format that is faster to produce and more useful to receive than a wall of bullet points.",
      ctaNote: "Free template. To build a meeting notes tool that automates this entirely, the Torvi Ops or PM track shows you how.",
    },
  },
  {
    slug: "standup-notes-template",
    title: "Standup Notes Template — Free | Torvi",
    h1: "Standup notes template",
    metaDescription: "A standup notes template for async and sync standups. Yesterday, today, blockers — structured and scannable. Free.",
    keyword: "standup notes template",
    cluster: "meetings_and_action_items",
    pageType: "starter_pack",
    priorityScore: 31.9,
    body: {
      intro: "Standups fail when they turn into status meetings. This template keeps them tight — three fields, no prose, optimised for async reading. Works for Slack standups, Notion check-ins, and live meetings.",
      whatYouGet: [
        "Standup format: yesterday (done), today (planned), blockers — with a context field for anything that needs discussion",
        "Team standup rollup template: aggregate view across all team members",
        "AI prompt to generate a standup from your task management tool or notes",
        "Async standup guide: how to run standups that do not require a meeting",
      ],
      whoItsFor: "Team leads, PMs, and ops managers who run standups and want a format that is quick to complete and useful to read — without another 15-minute meeting.",
      ctaNote: "Free template. To build an automated standup tool that pulls from your task tracker, the Torvi Ops track covers it in Week 1.",
    },
  },
  {
    slug: "weekly-planning-template",
    title: "Weekly Planning Template — Free Download | Torvi",
    h1: "Weekly planning template",
    metaDescription: "A weekly planning template for senior professionals. Priorities, time blocks, and end-of-week review. Free download.",
    keyword: "weekly planning template",
    cluster: "meetings_and_action_items",
    pageType: "starter_pack",
    priorityScore: 30.2,
    body: {
      intro: "Weekly planning works when it is specific enough to guide daily decisions and flexible enough to absorb the unexpected. This template gives you that balance — a 15-minute Sunday or Monday process that sets the week up clearly.",
      whatYouGet: [
        "Weekly plan structure: top three priorities, time blocks for focus work, meetings review, and end-of-week reflection",
        "AI prompt to generate a weekly plan from your task list, calendar, and last week's review",
        "30-minute end-of-week review format",
        "Worked example from a senior ops manager's weekly review",
      ],
      whoItsFor: "Senior professionals who feel reactive and want a simple weekly planning practice that keeps them focused on what actually matters.",
      ctaNote: "Free template. If you want to build a weekly planning tool for your team, the Torvi run gives you the path from idea to shipped in four weeks.",
    },
  },
  {
    slug: "retrospective-template",
    title: "Retrospective Template — Free | Torvi",
    h1: "Retrospective template",
    metaDescription: "A practical retrospective template for teams and projects. What worked, what did not, what to change. Free download with AI prompt.",
    keyword: "retrospective template",
    cluster: "meetings_and_action_items",
    pageType: "starter_pack",
    priorityScore: 25.9,
    body: {
      intro: "Retrospectives are the most skipped ceremony in most teams. Usually because they feel like a complaints session with no outputs. This template changes that — structured enough to produce real improvements, fast enough to run in 45 minutes.",
      whatYouGet: [
        "Retro format: what went well, what was harder than expected, what to do differently, and one experiment to try",
        "AI prompt to synthesise retro input from async contributions",
        "Facilitation guide for running a retro that produces actions, not just observations",
        "Worked example from a project team after a challenging sprint",
      ],
      whoItsFor: "Team leads and project managers who run retrospectives and want a format that produces real change, not just a record of complaints.",
      ctaNote: "Free template. To build a retro and continuous improvement tool for your team, the Torvi Ops track is the guided path.",
    },
  },
  {
    slug: "meeting-minutes-generator",
    title: "AI Meeting Minutes Generator — Guide | Torvi",
    h1: "Meeting minutes generator",
    metaDescription: "How to automate meeting minutes generation with AI: tools, prompts, and workflows. Includes free template.",
    keyword: "meeting minutes generator",
    cluster: "meetings_and_action_items",
    pageType: "resource_page",
    priorityScore: 38.0,
    body: {
      intro: "Generating meeting minutes with AI is now a three-step workflow: transcribe, prompt, format. The challenge is getting consistent, high-quality output rather than a reformatted wall of text. This guide covers the tools and prompts that actually produce usable minutes.",
      whatYouGet: [
        "Transcription tool comparison for meeting minutes: Otter, Fireflies, Notion AI, and direct ChatGPT/Claude upload",
        "Two-stage prompt approach: first pass for extraction, second pass for professional formatting",
        "Output routing: how to get generated minutes into your preferred tool automatically",
        "A worked end-to-end example with a real 30-minute team meeting",
      ],
      whoItsFor: "Chiefs of Staff, project managers, and executive assistants who take minutes for multiple recurring meetings and want to eliminate the 30-minute post-meeting writing session.",
      ctaNote: "Free guide. To build a custom meeting minutes tool integrated with your specific workflow, the Torvi Ops track is the structured path.",
    },
  },
];
