import type { PSEOPage } from "../pages";

export const opsToolPages: PSEOPage[] = [
  {
    slug: "task-routing-template",
    title: "Task Routing Template — Free Download | Torvi",
    h1: "Task routing template",
    metaDescription: "A task routing template for ops teams. Intake criteria, routing logic, owner assignment, and escalation paths. Free.",
    keyword: "task routing template",
    cluster: "ops_ai_tools",
    pageType: "template_page",
    priorityScore: 49.6,
    body: {
      intro: "Task routing is one of the highest-value automations an ops team can build — and one of the least structured. Without a clear routing logic, everything becomes a judgment call and everything is slow. This template forces the logic out of people's heads and into a system.",
      whatYouGet: [
        "Routing logic template: intake criteria, condition rules, owner assignment, escalation path, and SLA",
        "AI prompt to generate routing rules from a description of your current intake process",
        "Edge case capture checklist: the ten routing scenarios teams most often skip",
        "Worked example for a project intake routing system",
      ],
      whoItsFor: "Operations managers and BizOps leads who handle incoming requests from multiple sources and want to replace ad hoc routing with a documented, repeatable system.",
      ctaNote: "Free template. To build an automated task routing tool that applies this logic without manual intervention, the Torvi Ops track is how.",
    },
  },
  {
    slug: "sop-template",
    title: "SOP Template — Free Download | Torvi",
    h1: "SOP template",
    metaDescription: "A practical SOP template for operations teams. Process steps, decision points, owners, and edge cases. Free download.",
    keyword: "sop template",
    cluster: "ops_ai_tools",
    pageType: "starter_pack",
    priorityScore: 35.8,
    body: {
      intro: "A good SOP is specific enough to follow, short enough to read, and structured enough to update. Most SOPs fail on all three. This template hits the balance: a clean format that captures the real process without turning into a 20-page document nobody uses.",
      whatYouGet: [
        "SOP structure: purpose, scope, process steps with decision points, owner at each step, edge cases, and version log",
        "AI prompt to generate a first-draft SOP from process notes or an interview transcript",
        "Update workflow: how to keep SOPs current without a manual review cycle",
        "Worked example: ops intake SOP for a cross-functional team",
      ],
      whoItsFor: "Operations managers responsible for process documentation who need SOPs that are actually followed — not filed and forgotten.",
      ctaNote: "Free template. To build a tool that generates and maintains SOPs from your team's actual process data, the Torvi Ops track covers it.",
    },
  },
  {
    slug: "weekly-reporting-workflow-software",
    title: "How to Automate Weekly Reporting — Guide | Torvi",
    h1: "Weekly reporting workflow",
    metaDescription: "A guide to automating your weekly reporting workflow with AI. Tools, prompts, and integration patterns for ops and PM teams.",
    keyword: "weekly reporting workflow software",
    cluster: "ops_ai_tools",
    pageType: "template_page",
    priorityScore: 37.0,
    body: {
      intro: "Weekly reports take too long because the workflow is manual end to end. Data from multiple sources, summarised by hand, formatted in a template, sent to a distribution list. This guide covers the automation layer: how to connect those steps so the report builds itself.",
      whatYouGet: [
        "Weekly reporting workflow map: data sources → extraction → summarisation → formatting → distribution",
        "AI prompt stack for automated summarisation and formatting",
        "Integration patterns for common data sources: Google Sheets, Notion, Linear, Jira",
        "A worked example: a weekly ops report generated from a Notion database",
      ],
      whoItsFor: "Operations managers and PMs who produce the same weekly report every Friday and want to eliminate the 45-minute production process without sacrificing quality.",
      ctaNote: "Free guide. To build a custom weekly reporting tool for your team, the Torvi Ops track is the guided path to ship it in four weeks.",
    },
  },
];

export const pmToolPages: PSEOPage[] = [
  {
    slug: "competitive-analysis-template-for-product-managers",
    title: "Competitive Analysis Template for Product Managers — Free | Torvi",
    h1: "Competitive analysis template for product managers",
    metaDescription: "A structured competitive analysis template for PMs. Feature matrix, positioning, strengths, gaps. Free download with AI prompt.",
    keyword: "competitive analysis template for product managers",
    cluster: "pm_ai_tools",
    pageType: "starter_pack",
    priorityScore: 39.0,
    body: {
      intro: "Competitive analysis done well gives you three things: an honest view of where you are stronger, where you are weaker, and where nobody is serving the user well. This template forces that honesty — it is structured around gaps and opportunities, not just feature lists.",
      whatYouGet: [
        "Competitive analysis structure: feature matrix, positioning map, strengths/weaknesses per competitor, unmet user needs, and strategic implications",
        "AI prompt to generate an initial analysis from competitor websites, reviews, and your product knowledge",
        "Positioning gap identification prompt: where is the market not being served?",
        "Worked example for a B2B workflow tool",
      ],
      whoItsFor: "Product managers who run quarterly or ad hoc competitive reviews and want a consistent format that produces strategic insight, not just a spreadsheet of features.",
      ctaNote: "Free template. To build a competitive intelligence tool for your team, the Torvi PM track is the guided path.",
    },
  },
  {
    slug: "user-research-template-for-product-managers",
    title: "User Research Template for Product Managers — Free | Torvi",
    h1: "User research template for product managers",
    metaDescription: "A PM user research template: discussion guide, synthesis format, insight extraction, and recommendations. Free download.",
    keyword: "user research template for product managers",
    cluster: "pm_ai_tools",
    pageType: "template_page",
    priorityScore: 35.2,
    body: {
      intro: "User research is only as good as the synthesis. Most PMs are decent at running interviews; most are bad at turning them into clear product insights. This template covers both: the discussion guide that gets honest answers, and the synthesis format that produces actionable findings.",
      whatYouGet: [
        "Research discussion guide: context questions, job-to-be-done questions, pain point depth, and validation questions",
        "Synthesis template: themes, direct quotes, insights, open questions, and recommended actions",
        "AI prompt to synthesise findings from multiple interview transcripts",
        "Affinity mapping guide for large research volumes",
      ],
      whoItsFor: "Product managers who run user research regularly and want a process that produces usable insights, not just a folder full of interview recordings.",
      ctaNote: "Free template. To build a research synthesis tool for your team, the Torvi PM track covers it.",
    },
  },
  {
    slug: "meeting-notes-template-for-product-managers",
    title: "Meeting Notes Template for Product Managers — Free | Torvi",
    h1: "Meeting notes template for product managers",
    metaDescription: "A PM meeting notes template covering decisions, action items, open questions, and context. AI prompt for fast generation. Free.",
    keyword: "meeting notes template for product managers",
    cluster: "pm_ai_tools",
    pageType: "template_page",
    priorityScore: 33.7,
    body: {
      intro: "PM meeting notes have a specific job: capture what was decided, who owns what, and what questions are still open — so the meeting does not need to happen again. This template is built around that job, not around documenting everything that was said.",
      whatYouGet: [
        "PM meeting notes format: decisions made, open questions, action items with owners, context note for async readers",
        "Variants for product review, sprint planning, stakeholder sync, and design review",
        "AI prompt to generate notes from a recording or rough bullet points",
        "Distribution guide: who needs what level of detail",
      ],
      whoItsFor: "Product managers who are in five or more meetings a week and want a consistent, fast meeting notes process that keeps everyone aligned without a 30-minute write-up.",
      ctaNote: "Free template. To build an automated meeting notes tool for your team, the Torvi PM track covers it.",
    },
  },
  {
    slug: "chatgpt-meeting-notes-for-product-managers",
    title: "ChatGPT for Meeting Notes — PM Guide | Torvi",
    h1: "ChatGPT for meeting notes",
    metaDescription: "How PMs use ChatGPT for meeting notes: prompts, workflow, and integration with Notion, Linear, and Jira. Free guide.",
    keyword: "chatgpt prompts for meeting notes",
    cluster: "pm_ai_tools",
    pageType: "resource_page",
    priorityScore: 36.7,
    body: {
      intro: "Product managers are in more meetings than anyone. Using ChatGPT to handle the notes is one of the highest-leverage workflow changes a PM can make — if the prompts are right and the process is structured. This guide covers both.",
      whatYouGet: [
        "3-step workflow: transcript or rough notes → extraction prompt → formatted notes",
        "PM-specific prompt variants for product review, design critique, stakeholder sync, and sprint planning",
        "Integration patterns: how to route generated notes to Notion, Linear, or Jira automatically",
        "Worked example: a 45-minute product review meeting turned into structured notes in 3 minutes",
      ],
      whoItsFor: "Product managers who already use ChatGPT but want a repeatable, consistent workflow for meeting notes — not an improvised prompt every time.",
      ctaNote: "Free guide. To build a meeting notes tool that runs this process automatically for your team, the Torvi PM track is the path.",
    },
  },
  {
    slug: "product-requirements-template-for-product-managers",
    title: "Product Requirements Template for PMs — Free | Torvi",
    h1: "Product requirements template for product managers",
    metaDescription: "A product requirements template built for PMs: user stories, functional and non-functional requirements, and acceptance criteria. Free.",
    keyword: "product requirements template for product managers",
    cluster: "pm_ai_tools",
    pageType: "template_page",
    priorityScore: 31.2,
    body: {
      intro: "Requirements documents written by PMs get engineering work started quickly or slowly, depending on how complete they are. This template covers the full picture — from user stories to non-functional requirements to acceptance criteria — so engineering can start without a clarification meeting.",
      whatYouGet: [
        "PM requirements template: problem statement, user stories, functional requirements, non-functional requirements, acceptance criteria, and open questions",
        "AI prompt to generate requirements from discovery notes or user research",
        "Requirements completeness checklist: the ten things most PM requirements docs are missing",
        "Worked example for an internal PM tool",
      ],
      whoItsFor: "Product managers who write requirements for engineering teams and want a format that is complete enough to prevent back-and-forth without being a 30-page document.",
      ctaNote: "Free template. To build a requirements generation tool for your team, the Torvi PM track covers it.",
    },
  },
  {
    slug: "stakeholder-updates-template-for-product-managers",
    title: "Stakeholder Updates Template for Product Managers — Free | Torvi",
    h1: "Stakeholder updates template for product managers",
    metaDescription: "A PM stakeholder updates template. Progress, decisions, risks, and next steps — structured for exec and cross-functional audiences. Free.",
    keyword: "stakeholder updates template for product managers",
    cluster: "pm_ai_tools",
    pageType: "template_page",
    priorityScore: 33.1,
    body: {
      intro: "Stakeholder updates are how PMs build trust and manage expectations across the organisation. The format matters as much as the content — too long and nobody reads it, too short and you look like you are hiding something. This template hits the right balance.",
      whatYouGet: [
        "Stakeholder update structure: summary status (RAG), progress this period, upcoming milestones, decisions needed, risks, and appendix for detail",
        "Audience calibration guide: what exec stakeholders need vs. delivery team vs. external partners",
        "AI prompt to generate an update from your project notes and last period's update",
        "Weekly and monthly variants",
      ],
      whoItsFor: "Product managers who send stakeholder updates to senior audiences and want a format that keeps people informed without creating work for themselves every week.",
      ctaNote: "Free template. To build a stakeholder update automation tool for your team, the Torvi PM track covers it.",
    },
  },
];
