import type { PSEOPage } from "../pages";

export const prdRequirementsPages: PSEOPage[] = [
  {
    slug: "prd-template",
    title: "PRD Template — Free Download for Product Managers | Torvi",
    h1: "PRD template",
    metaDescription: "A clean, practical PRD template for product managers. Covers context, problem, requirements, non-requirements, and open questions. Free.",
    keyword: "prd template",
    cluster: "prd_and_requirements",
    pageType: "starter_pack",
    priorityScore: 36.2,
    body: {
      intro: "Most PRD templates are either too long to fill out or too short to be useful. This one hits the middle: enough structure to force clear thinking, lean enough that engineering will actually read it.",
      whatYouGet: [
        "One-page PRD structure: context block, problem statement, success metric, in-scope requirements, out-of-scope list, open questions",
        "AI prompt to generate a first draft from your discovery notes",
        "Variants for feature PRDs, MVP PRDs, and internal tool PRDs",
        "Worked example: PRD for an internal reporting tool",
      ],
      whoItsFor: "Product managers who write PRDs regularly and want a format that is fast to fill out and easy for stakeholders to read and act on.",
      ctaNote: "Free template. To build a PRD generation tool that pulls from your research system, the Torvi PM track covers it in Week 2.",
    },
  },
  {
    slug: "requirements-template",
    title: "Requirements Template — Free Download | Torvi",
    h1: "Requirements template",
    metaDescription: "A clean requirements template for product and engineering teams. Functional, non-functional, and user story formats. Free download.",
    keyword: "requirements template",
    cluster: "prd_and_requirements",
    pageType: "starter_pack",
    priorityScore: 38.6,
    body: {
      intro: "Vague requirements are the most expensive thing in software development. This template forces specificity: every requirement has a clear condition, a testable outcome, and a stated assumption.",
      whatYouGet: [
        "Three format variants: functional requirements list, non-functional requirements spec, and user story format",
        "A requirements QA checklist: testability, ambiguity, and completeness checks",
        "AI prompt to generate requirements from discovery interviews or problem statements",
        "Worked example: requirements for an ops intake tool",
      ],
      whoItsFor: "PMs, senior engineers, and technical leads who write requirements as part of a regular process and want a format that reduces back-and-forth with engineering.",
      ctaNote: "Free template. To build a requirements generator for your team, the Torvi PM track walks you through it.",
    },
  },
  {
    slug: "product-requirements-template",
    title: "Product Requirements Template — Free | Torvi",
    h1: "Product requirements template",
    metaDescription: "A practical product requirements template that covers user needs, business constraints, and technical specifications. Free download.",
    keyword: "product requirements template",
    cluster: "prd_and_requirements",
    pageType: "template_page",
    priorityScore: 50.0,
    body: {
      intro: "Product requirements live at the intersection of user needs, business constraints, and technical feasibility. This template holds all three in one place — so you stop losing context between your discovery doc, your PRD, and your engineering spec.",
      whatYouGet: [
        "Unified requirements template: user context, business context, functional requirements, non-functional requirements, constraints, and dependencies",
        "AI prompt to populate requirements from user research or stakeholder interviews",
        "Prioritisation column for must-have vs. nice-to-have vs. out-of-scope",
        "Worked example for an internal workflow tool",
      ],
      whoItsFor: "Product managers working on internal tools, SaaS features, or workflow automation who need a requirements format that engineering, design, and leadership can all work from.",
      ctaNote: "Free download. If you want to build a product requirements tool that generates this from your discovery inputs automatically, the Torvi PM track covers it.",
    },
  },
  {
    slug: "product-spec-template",
    title: "Product Spec Template — Free Download | Torvi",
    h1: "Product spec template",
    metaDescription: "A lean product spec template for teams shipping fast. Covers the problem, the solution scope, and the definition of done. Free.",
    keyword: "product spec template",
    cluster: "prd_and_requirements",
    pageType: "template_page",
    priorityScore: 38.2,
    body: {
      intro: "A product spec should answer three questions: what problem does this solve, what exactly are we building, and how will we know it is done. This template is built around those three questions — nothing more, nothing less.",
      whatYouGet: [
        "Lean spec format: problem statement, solution scope, requirements, definition of done, known risks",
        "AI prompt to write a first-draft spec from a brief or discovery notes",
        "Variant for feature specs vs. full product specs",
        "Worked example for a reporting automation tool",
      ],
      whoItsFor: "PMs and technical leads at startups and scale-ups who want a spec format that moves fast without losing clarity.",
      ctaNote: "Free template. To build spec generation into your product workflow, the Torvi PM track is the guided path.",
    },
  },
  {
    slug: "non-functional-requirements-template",
    title: "Non-Functional Requirements Template — Free | Torvi",
    h1: "Non-functional requirements template",
    metaDescription: "A practical non-functional requirements template covering performance, security, reliability, and scalability. Free download.",
    keyword: "non functional requirements template",
    cluster: "prd_and_requirements",
    pageType: "starter_pack",
    priorityScore: 43.6,
    body: {
      intro: "Non-functional requirements are what get skipped in a rush and what cause outages in production. This template makes them impossible to skip — a structured format that covers every non-functional dimension your engineering team needs to plan against.",
      whatYouGet: [
        "NFR categories covered: performance, reliability, security, scalability, maintainability, and accessibility",
        "For each category: requirement statement, measurement definition, and acceptance threshold",
        "AI prompt to generate NFRs from a product brief or use case description",
        "Worked example for an internal ops dashboard",
      ],
      whoItsFor: "PMs and technical leads building internal tools or SaaS features who need a complete NFR format that engineering can design against without ambiguity.",
      ctaNote: "Free template. To build a tool that generates comprehensive requirements from your product inputs, the Torvi PM track covers it.",
    },
  },
  {
    slug: "requirements-template-for-saas",
    title: "Requirements Template for SaaS — Free | Torvi",
    h1: "Requirements template for SaaS",
    metaDescription: "A requirements template built for SaaS products: multi-tenancy, permissions, billing, and API considerations included. Free download.",
    keyword: "requirements template for saas",
    cluster: "prd_and_requirements",
    pageType: "starter_pack",
    priorityScore: 39.7,
    body: {
      intro: "SaaS requirements have recurring patterns that generic templates miss: multi-tenancy, role-based access, billing state, API contracts, and data isolation. This template covers all of them so you do not find out in code review that you forgot something fundamental.",
      whatYouGet: [
        "SaaS-specific requirement categories: authentication, authorisation, multi-tenancy, billing states, API contracts, data retention, and audit logging",
        "Checklist of SaaS requirements that teams commonly skip in early-stage products",
        "AI prompt to audit your existing requirements for SaaS completeness",
        "Worked example for a B2B workflow tool",
      ],
      whoItsFor: "PMs and founders building SaaS products who want to catch the common requirements gaps before they become engineering rework.",
      ctaNote: "Free template. To build a requirements generation tool for your SaaS team, the Torvi PM track walks you through it.",
    },
  },
  {
    slug: "requirements-template-for-mvp",
    title: "Requirements Template for MVP — Free | Torvi",
    h1: "Requirements template for MVP",
    metaDescription: "A lean requirements template for MVP builds. Ruthlessly scoped — only what you need to validate the core idea. Free download.",
    keyword: "requirements template for mvp",
    cluster: "prd_and_requirements",
    pageType: "starter_pack",
    priorityScore: 33.8,
    body: {
      intro: "MVP requirements have one job: define the minimum viable thing that tests the core assumption. This template forces that discipline — it has an explicit 'not building' column and a single validation question that every requirement must answer.",
      whatYouGet: [
        "MVP requirements format: core assumption, minimum feature set, explicit exclusions, validation method, and success threshold",
        "A scope creep blocker: a one-question test every proposed requirement must pass",
        "AI prompt to trim an existing requirements list to its MVP core",
        "Worked example: MVP requirements for an internal intake tool",
      ],
      whoItsFor: "PMs, founders, and senior professionals building their first internal tool who need to scope ruthlessly and start building without getting lost in edge cases.",
      ctaNote: "Free template. If you want a guided process to take your MVP from requirements to shipped tool in four weeks, Torvi is the structured path.",
    },
  },
  {
    slug: "prd-template-for-automation",
    title: "PRD Template for Automation — Free | Torvi",
    h1: "PRD template for automation",
    metaDescription: "A PRD template built for automation projects: trigger, logic, output, error handling, and monitoring. Free download.",
    keyword: "prd template for automation",
    cluster: "prd_and_requirements",
    pageType: "starter_pack",
    priorityScore: 46.5,
    body: {
      intro: "Automation PRDs fail when they skip the failure states. This template is built for automations specifically: it forces you to define the trigger, the logic, the output, what happens when it breaks, and how you will know it is working.",
      whatYouGet: [
        "Automation PRD sections: trigger definition, logic flow, output specification, error handling, monitoring and alerting, and rollback plan",
        "AI prompt to generate an automation PRD from a workflow description",
        "Edge case identification prompt for automation logic",
        "Worked example: automated weekly report generator PRD",
      ],
      whoItsFor: "PMs and ops leads building workflow automation tools who need a PRD format that covers the operational realities of automations, not just the happy path.",
      ctaNote: "Free template. To build and ship your automation in four weeks with a guided process, the Torvi Ops or PM track is how.",
    },
  },
  {
    slug: "requirements-template-for-automation",
    title: "Requirements Template for Automation — Free | Torvi",
    h1: "Requirements template for automation",
    metaDescription: "A requirements template for automation projects covering triggers, conditions, actions, error states, and monitoring. Free.",
    keyword: "requirements template for automation",
    cluster: "prd_and_requirements",
    pageType: "template_page",
    priorityScore: 39.4,
    body: {
      intro: "Automation requirements need to cover the full state machine, not just the happy path. This template is structured around that reality — every requirement has a trigger, a condition, an action, an error state, and a monitoring signal.",
      whatYouGet: [
        "Automation requirements format: trigger, condition, action, error handling, and monitoring for each requirement",
        "Integration requirements template for connecting to external tools and APIs",
        "Data requirements template: input format, output format, and transformation logic",
        "Worked example for an ops intake routing automation",
      ],
      whoItsFor: "Ops managers and PMs building workflow automation tools who need requirements that engineering can implement without a follow-up meeting for every edge case.",
      ctaNote: "Free template. To ship your automation in four weeks, the Torvi run gives you the guided path from requirements to deployed tool.",
    },
  },
  {
    slug: "requirements-template-for-b2b",
    title: "Requirements Template for B2B Tools — Free | Torvi",
    h1: "Requirements template for B2B",
    metaDescription: "A requirements template built for B2B tools: admin, permissions, reporting, integrations, and enterprise considerations. Free.",
    keyword: "requirements template for b2b",
    cluster: "prd_and_requirements",
    pageType: "template_page",
    priorityScore: 34.0,
    body: {
      intro: "B2B tools have requirements that consumer products do not: admin controls, team-level permissions, audit trails, enterprise SSO, and reporting that procurement can defend. This template covers all of them.",
      whatYouGet: [
        "B2B-specific requirement categories: admin controls, role-based permissions, audit logging, enterprise integrations, reporting and export, and data residency",
        "Procurement and compliance checklist: requirements that enterprise buyers always ask for",
        "AI prompt to identify missing B2B requirements in your existing spec",
        "Worked example for a B2B internal tool",
      ],
      whoItsFor: "PMs building tools for business customers who need to think beyond the core feature and into the operational and compliance requirements that enterprise buyers need.",
      ctaNote: "Free template. To build and ship your B2B tool in four weeks, the Torvi PM or Consultant track gives you the guided path.",
    },
  },
  {
    slug: "prd-template-for-internal-tool",
    title: "PRD Template for Internal Tools — Free | Torvi",
    h1: "PRD template for internal tool",
    metaDescription: "A lean PRD template built for internal tools: user, workflow, integration, and success metric. Free download.",
    keyword: "prd template for internal tool",
    cluster: "prd_and_requirements",
    pageType: "template_page",
    priorityScore: 31.1,
    body: {
      intro: "Internal tool PRDs are different from product PRDs. You have one real user (your team), one clear workflow, and one measurable outcome. This template reflects that reality — it is leaner, more specific, and focused on the handoff between you and whoever builds it.",
      whatYouGet: [
        "Internal tool PRD format: user description, current workflow, target workflow, requirements, success metric, and non-requirements",
        "AI prompt to generate a first-draft PRD from a description of the current workflow",
        "Questions to clarify scope before you start building",
        "Worked example: PRD for an internal project intake tool",
      ],
      whoItsFor: "PMs, ops managers, and consultants building tools for their own team or client teams — not shipping to external users.",
      ctaNote: "Free template. This is exactly what Week 0 of the Torvi run produces — a clear brief for the tool you are building.",
    },
  },
];
