import type { PSEOPage } from "../pages";

export const promptTemplatePages: PSEOPage[] = [
  {
    slug: "chatgpt-prompts-for-stakeholder-update",
    title: "ChatGPT Prompts for Stakeholder Updates — Free Templates | Torvi",
    h1: "ChatGPT prompts for stakeholder updates",
    metaDescription: "Copy-paste ChatGPT prompts for writing stakeholder updates that get read. Covers weekly status, escalation, and exec summaries.",
    keyword: "chatgpt prompts for stakeholder update",
    cluster: "prompt_templates",
    pageType: "resource_page",
    priorityScore: 61.9,
    body: {
      intro: "Stakeholder updates are the most under-engineered communication in most organisations. People write them last, rush them, and wonder why nobody reads them. These prompts force the right structure: what changed, what it means, what you need.",
      whatYouGet: [
        "6 prompt variants: weekly status, decision required, risk escalation, exec summary, all-clear, and blocker removed",
        "Tone calibration guide for different stakeholder types: C-suite, delivery team, external client",
        "Template output format that works in email, Notion, or Slack",
        "Worked examples with before/after comparisons",
      ],
      whoItsFor: "PMs, project leads, and consultants who send stakeholder updates weekly and want a consistent, professional format without the 30-minute writing session.",
      ctaNote: "Free templates. If you want to build a stakeholder update tool that pulls from your project data automatically, the Torvi PM or Consultant track covers it.",
    },
  },
  {
    slug: "prompt-library-for-status-update",
    title: "Prompt Library for Status Updates — Free | Torvi",
    h1: "Prompt library for status updates",
    metaDescription: "A curated library of prompts for writing project and work status updates fast. RAG format, plain-text, and exec summary variants.",
    keyword: "prompt library for status update",
    cluster: "prompt_templates",
    pageType: "starter_pack",
    priorityScore: 58.3,
    body: {
      intro: "A good status update takes five minutes to write and five seconds to read. This prompt library gives you the starting points to get there — structured prompts for every status update format you will ever need.",
      whatYouGet: [
        "12 prompts covering: RAG status, milestone summary, risk log, decision log, next steps, and retrospective snapshot",
        "Three output lengths: one-liner, paragraph, and full one-pager",
        "System prompt for consistent tone and style across your updates",
        "Worked examples for project and operational contexts",
      ],
      whoItsFor: "Operations managers, PMs, and team leads who send recurring status updates and want to stop starting from a blank page each time.",
      ctaNote: "Download the library free. To build a status update tool that generates these from your actual project data, the Torvi run is how.",
    },
  },
  {
    slug: "prompt-library-for-sop",
    title: "Prompt Library for SOPs — Free Templates | Torvi",
    h1: "Prompt library for SOPs",
    metaDescription: "AI prompt library for writing standard operating procedures. Covers structure, tone, edge cases, and version control. Free download.",
    keyword: "prompt library for sop",
    cluster: "prompt_templates",
    pageType: "starter_pack",
    priorityScore: 47.6,
    body: {
      intro: "SOPs fail for two reasons: they are written once and never updated, or they are too generic to follow. This prompt library addresses both — prompts for first-draft generation, edge case coverage, and revision from real usage feedback.",
      whatYouGet: [
        "8 prompts: first-draft SOP from process notes, step-level detail expansion, edge case identification, version delta summary, plain-language rewrite, and approval checklist",
        "Format guide for different SOP types: linear process, decision tree, checklist format",
        "Worked example: ops intake SOP built from interview notes",
        "A guide on feeding context to get accurate procedure steps, not generic ones",
      ],
      whoItsFor: "Operations leads and Chiefs of Staff responsible for process documentation who want to go from messy notes to a usable SOP in under an hour.",
      ctaNote: "Free library. If you want to build a tool that generates and maintains SOPs from your team's actual process activity, the Torvi Ops track shows you how.",
    },
  },
  {
    slug: "chatgpt-prompts-for-work",
    title: "ChatGPT Prompts for Work — Free Library | Torvi",
    h1: "ChatGPT prompts for work",
    metaDescription: "A practical library of ChatGPT prompts for real work tasks: planning, writing, analysis, reporting, and more. Free, no login.",
    keyword: "chatgpt prompts for work",
    cluster: "prompt_templates",
    pageType: "resource_page",
    priorityScore: 45.9,
    body: {
      intro: "Most people use ChatGPT for work the same way they use Google — one improvised question, inconsistent results. This library gives you structured prompts for the work tasks that actually take time: writing reports, planning work, summarising meetings, drafting updates.",
      whatYouGet: [
        "50+ prompts organised by work category: planning, reporting, writing, analysis, summarisation, and communications",
        "Each prompt includes purpose, input format, expected output, and one worked example",
        "Role-specific sections for PMs, ops managers, and consultants",
        "A guide on building a personal prompt system from this library",
      ],
      whoItsFor: "Senior professionals who use AI tools daily but want a reliable library to pull from instead of improvising prompts from scratch.",
      ctaNote: "Free library. If you want to embed these into a tool that automates the workflow entirely, the Torvi run is the structured path.",
    },
  },
  {
    slug: "prompt-library-for-roadmap-prioritization",
    title: "Prompt Library for Roadmap Prioritisation — Free | Torvi",
    h1: "Prompt library for roadmap prioritisation",
    metaDescription: "AI prompts for roadmap prioritisation: scoring frameworks, trade-off analysis, and stakeholder-ready summaries. Free download.",
    keyword: "prompt library for roadmap prioritization",
    cluster: "prompt_templates",
    pageType: "resource_page",
    priorityScore: 42.4,
    body: {
      intro: "Roadmap prioritisation is part analysis, part negotiation, part communication. These prompts help with all three — from scoring candidate features against a framework to explaining the trade-offs to a sceptical stakeholder.",
      whatYouGet: [
        "Prompts for five frameworks: RICE, ICE, MoSCoW, cost of delay, and custom scoring",
        "Trade-off analysis prompt that surfaces the real constraints behind competing priorities",
        "Stakeholder communication prompts: decision rationale, what got cut and why, next review date",
        "Worked example: quarterly roadmap review from a product team",
      ],
      whoItsFor: "Product managers who run quarterly or monthly roadmap reviews and want to spend less time in spreadsheets and more time on the actual decision.",
      ctaNote: "Free prompts. To build a prioritisation tool your team uses every sprint, the Torvi PM track covers it in Weeks 1–2.",
    },
  },
  {
    slug: "prompt-templates-for-operations",
    title: "Prompt Templates for Operations — Free Pack | Torvi",
    h1: "Prompt templates for operations",
    metaDescription: "Free prompt templates for operations teams: SOPs, status reports, intake briefs, routing logic, and weekly reviews.",
    keyword: "prompt templates for operations",
    cluster: "prompt_templates",
    pageType: "starter_pack",
    priorityScore: 39.9,
    body: {
      intro: "Operations work is repetitive by design. The prompts should be too. This pack covers the recurring outputs that ops teams produce every week — from status reports to intake briefs to SOP documentation — so you can stop rewriting from scratch.",
      whatYouGet: [
        "10 prompt templates: weekly ops review, intake brief, routing decision log, SOP draft, escalation summary, vendor check-in, KPI snapshot, handoff note, retro summary, and planning brief",
        "Each template includes the prompt, the ideal input format, and sample output",
        "A guide on chaining prompts for longer ops documents",
        "Ops-specific tone guidance: direct, unambiguous, actionable",
      ],
      whoItsFor: "Operations managers, BizOps leads, and Chiefs of Staff who produce the same document types week after week and want to do it in less time.",
      ctaNote: "Free pack. If you want to automate the ops workflow entirely — building a tool that generates these from live data — the Torvi Ops track walks you through it.",
    },
  },
  {
    slug: "chatgpt-prompts-for-weekly-report",
    title: "ChatGPT Prompts for Weekly Reports — Free | Torvi",
    h1: "ChatGPT prompts for weekly reports",
    metaDescription: "ChatGPT prompts for writing weekly progress reports fast. Covers team updates, exec summaries, and client-facing formats.",
    keyword: "chatgpt prompts for weekly report",
    cluster: "prompt_templates",
    pageType: "template_page",
    priorityScore: 38.0,
    body: {
      intro: "Weekly reports exist to prevent surprises. These prompts turn your scattered notes, Slack threads, and meeting summaries into a clean, structured weekly report in minutes — not the 45 minutes it currently takes.",
      whatYouGet: [
        "5 prompt variants: internal team report, exec summary, client-facing update, cross-team standup, and project milestone report",
        "A two-step approach: extract key points first, then format for audience",
        "Tone guide for different report recipients",
        "Worked example with a real ops week's worth of notes transformed into a clean report",
      ],
      whoItsFor: "Team leads and ops managers who write weekly reports every Friday and want to get it done in under 15 minutes without cutting corners.",
      ctaNote: "Free prompts. To build an automated weekly reporting tool, the Torvi Ops track covers it in Week 2.",
    },
  },
  {
    slug: "prompt-library-for-requirements",
    title: "Prompt Library for Requirements — Free | Torvi",
    h1: "Prompt library for requirements",
    metaDescription: "AI prompts for writing product and feature requirements: functional, non-functional, user stories, and acceptance criteria.",
    keyword: "prompt library for requirements",
    cluster: "prompt_templates",
    pageType: "resource_page",
    priorityScore: 34.9,
    body: {
      intro: "Requirements are where precision matters most and where most teams cut corners. This prompt library gives you structured starting points for every requirements format — from user stories to non-functional specs — so you stop writing vague requirements that engineering has to interpret.",
      whatYouGet: [
        "10 prompts: functional requirements, non-functional requirements, user story, acceptance criteria, edge case identification, open questions, out-of-scope list, constraint documentation, dependency mapping, and definition of done",
        "Context-feeding guide: how to give AI the right inputs for accurate requirements",
        "QA prompt for reviewing requirements you have already written",
        "Worked example: internal intake tool requirements built from discovery notes",
      ],
      whoItsFor: "PMs and senior ICs who write requirements regularly and want a consistent, complete format that engineering can act on without a clarification meeting.",
      ctaNote: "Free library. To build a requirements generation tool for your team, the Torvi PM track covers it.",
    },
  },
  {
    slug: "chatgpt-prompts-for-client-diagnostic",
    title: "ChatGPT Prompts for Client Diagnostics — Free | Torvi",
    h1: "ChatGPT prompts for client diagnostics",
    metaDescription: "ChatGPT prompts for consultant client diagnostics: discovery questions, synthesis, gap analysis, and executive summary.",
    keyword: "chatgpt prompts for client diagnostic",
    cluster: "prompt_templates",
    pageType: "resource_page",
    priorityScore: 36.7,
    body: {
      intro: "A good client diagnostic surfaces the real problem, not the presenting problem. These prompts help you structure your discovery questions, synthesise interview outputs, identify the gaps between where the client is and where they want to be, and write the summary that opens the engagement.",
      whatYouGet: [
        "5 prompts: discovery question generation by function, interview synthesis, gap analysis, root cause identification, and exec summary",
        "A guide on feeding interview transcripts for synthesis (what to include, what to strip out)",
        "Output templates for the diagnostic summary document",
        "Worked example from a process transformation diagnostic",
      ],
      whoItsFor: "Independent consultants and transformation leads who run client diagnostics regularly and want a more consistent, faster process from discovery to findings.",
      ctaNote: "Free prompts. To build a client diagnostic tool you can deploy with clients directly, the Torvi Consultant track is how.",
    },
  },
];
