import type { PSEOPage } from "../pages";

export const reportingPages: PSEOPage[] = [
  {
    slug: "monthly-report-software",
    title: "How to Automate Monthly Reports — Guide | Torvi",
    h1: "Monthly report automation",
    metaDescription: "A guide to automating monthly reports with AI: data extraction, summarisation, formatting, and distribution. Free templates included.",
    keyword: "monthly report software",
    cluster: "reporting_automation",
    pageType: "template_page",
    priorityScore: 35.0,
    body: {
      intro: "Monthly reports are where most reporting automation efforts stall — not because the automation is hard, but because the monthly report format is less standardised than weekly reports and more likely to need narrative. This guide covers the AI-assisted approach that keeps the narrative quality high while cutting the production time in half.",
      whatYouGet: [
        "Monthly report workflow: data sources → automated extraction → AI summarisation → human narrative layer → distribution",
        "AI prompts for monthly executive summary, trend analysis, and variance commentary",
        "Template for the monthly report structure that works best for AI generation",
        "Worked example: monthly ops report for a cross-functional team",
      ],
      whoItsFor: "Operations managers and analysts who produce monthly reports and want to reduce the production time from half a day to under two hours without sacrificing quality.",
      ctaNote: "Free guide. To build an automated monthly reporting tool, the Torvi Ops track gives you the guided path to ship it.",
    },
  },
  {
    slug: "client-status-report-automation",
    title: "Client Status Report Automation — Guide | Torvi",
    h1: "Client status report automation",
    metaDescription: "How to automate client status reports with AI: data extraction, generation, and delivery. Guide for consultants and project teams.",
    keyword: "client status report automation",
    cluster: "reporting_automation",
    pageType: "template_page",
    priorityScore: 36.4,
    body: {
      intro: "Client status reports are the most repeatable deliverable in consulting — and the most time-consuming to produce manually. The automation opportunity is clear: extract data from your project notes, generate a structured report, and send it on schedule. This guide shows you how.",
      whatYouGet: [
        "Client status report automation workflow: project notes → AI extraction → structured report → review → client delivery",
        "AI prompts for RAG status summary, milestone progress, decision log, and risk update",
        "Integration options for generating reports from Notion, Airtable, or Google Sheets",
        "Worked example: weekly client status report generated from project notes in under 10 minutes",
      ],
      whoItsFor: "Independent consultants and small consulting firms who send weekly or biweekly client status reports and want to reduce production time from 90 minutes to under 15.",
      ctaNote: "Free guide. To build a client reporting tool that automates this end to end, the Torvi Consultant track is the path.",
    },
  },
  {
    slug: "monthly-report-template",
    title: "Monthly Report Template — Free Download | Torvi",
    h1: "Monthly report template",
    metaDescription: "A structured monthly report template for ops and PM teams. Executive summary, KPIs, milestones, risks, next month plan. Free.",
    keyword: "monthly report template",
    cluster: "reporting_automation",
    pageType: "template_page",
    priorityScore: 26.7,
    body: {
      intro: "A good monthly report answers three questions: what happened, what does it mean, and what is the plan. This template forces that structure — and nothing else — so monthly reports take 20 minutes to produce and two minutes to read.",
      whatYouGet: [
        "Monthly report structure: executive summary, KPI dashboard, milestone progress, key decisions, risks and mitigations, and next month plan",
        "AI prompt to generate a first-draft monthly report from your notes and data",
        "Audience variants: internal team, executive, board, and client",
        "Worked example for an ops function monthly report",
      ],
      whoItsFor: "Operations managers, project leads, and PMs who produce monthly reports for senior stakeholders and want a consistent format that is fast to produce and clear to read.",
      ctaNote: "Free template. To automate monthly report generation from your data sources, the Torvi Ops track walks you through building the tool.",
    },
  },
  {
    slug: "business-dashboard-template",
    title: "Business Dashboard Template — Free | Torvi",
    h1: "Business dashboard template",
    metaDescription: "A business dashboard template covering KPIs, targets, trends, and alerts. Built for ops and leadership teams. Free.",
    keyword: "business dashboard template",
    cluster: "reporting_automation",
    pageType: "starter_pack",
    priorityScore: 24.0,
    body: {
      intro: "Most business dashboards fail because they show everything without highlighting what matters. This template is designed around the opposite principle: choose the five metrics that drive the business, set the thresholds, and surface the signals clearly.",
      whatYouGet: [
        "Dashboard structure: primary KPIs with targets and RAG status, trend sparklines, key variances, and alert conditions",
        "Metric selection guide: how to choose the five numbers that actually matter for your function",
        "AI prompt to generate dashboard commentary from KPI data",
        "Variants for ops, product, revenue, and team dashboards",
      ],
      whoItsFor: "Operations managers and team leads who want a dashboard that drives decisions, not one that just displays data for its own sake.",
      ctaNote: "Free template. To build a live business dashboard tool that populates automatically from your data sources, the Torvi Ops track is the path.",
    },
  },
];

export const intakeRoutingPages: PSEOPage[] = [
  {
    slug: "ai-support-intake-tool",
    title: "AI Support Intake Tool — Guide and Templates | Torvi",
    h1: "AI support intake tool",
    metaDescription: "How to build an AI-powered support intake tool: classification, routing, and auto-response. Guide and templates for ops teams.",
    keyword: "ai support intake tool",
    cluster: "intake_and_routing",
    pageType: "template_page",
    priorityScore: 37.0,
    body: {
      intro: "Support intake is one of the clearest AI automation opportunities in ops. The incoming request has a type, a priority, and an owner — and AI can classify all three more accurately and faster than a human triaging a queue. This guide covers how to build that system.",
      whatYouGet: [
        "Support intake automation blueprint: intake capture → AI classification → routing logic → owner assignment → SLA tracking",
        "Classification prompt for common support request types",
        "Routing logic template for different team structures",
        "Worked example: internal IT support intake built and deployed in two weeks",
      ],
      whoItsFor: "Operations managers and Chiefs of Staff who manage a support or request intake function and want to replace manual triage with an automated classification and routing system.",
      ctaNote: "Free templates. To build and deploy your support intake tool, the Torvi Ops track gives you the four-week guided path.",
    },
  },
  {
    slug: "support-intake-template",
    title: "Support Intake Template — Free Download | Torvi",
    h1: "Support intake template",
    metaDescription: "A support intake template for ops teams. Request type, priority, context, and routing. Free download.",
    keyword: "support intake template",
    cluster: "intake_and_routing",
    pageType: "template_page",
    priorityScore: 34.3,
    body: {
      intro: "Support intake forms that ask too little produce incomplete requests that require follow-up. Forms that ask too much produce forms nobody fills in. This template hits the balance: the minimum fields needed to classify, route, and action a request without delay.",
      whatYouGet: [
        "Support intake form structure: request type, description, priority, urgency signals, and context fields",
        "Triage guide: classification criteria for your most common request types",
        "AI prompt to classify an incoming request and suggest the routing path",
        "Worked example for an internal ops support intake",
      ],
      whoItsFor: "Operations managers and team leads who handle incoming requests from multiple teams and want a consistent intake format that reduces the clarification back-and-forth.",
      ctaNote: "Free template. To build an automated intake and routing tool, the Torvi Ops track covers it.",
    },
  },
  {
    slug: "ai-project-intake-tool",
    title: "AI Project Intake Tool — Guide and Templates | Torvi",
    h1: "AI project intake tool",
    metaDescription: "How to build an AI-powered project intake tool: scoping questions, feasibility check, and routing to the right team. Free templates.",
    keyword: "ai project intake tool",
    cluster: "intake_and_routing",
    pageType: "template_page",
    priorityScore: 32.1,
    body: {
      intro: "Project intake is where poorly scoped requests enter and well-scoped projects need to come out. AI can help with the gap — by asking the right clarifying questions, checking feasibility against capacity, and routing to the right team with the right information.",
      whatYouGet: [
        "Project intake automation workflow: submission → AI scoping questions → feasibility check → prioritisation → routing",
        "Scoping question set for common project types (process improvement, tool build, reporting, integration)",
        "Prioritisation matrix template: effort vs. impact scoring with AI-assisted scoring prompts",
        "Worked example for a cross-functional ops team",
      ],
      whoItsFor: "Operations managers and portfolio leads who receive project requests from across the business and want a structured, consistent intake process that reduces the time from request to decision.",
      ctaNote: "Free templates. To build and deploy a project intake tool, the Torvi Ops track is the guided four-week path.",
    },
  },
  {
    slug: "client-intake-template",
    title: "Client Intake Template — Free Download | Torvi",
    h1: "Client intake template",
    metaDescription: "A client intake template for consultants. Situation, objectives, constraints, timeline, and budget. Free download.",
    keyword: "client intake template",
    cluster: "intake_and_routing",
    pageType: "template_page",
    priorityScore: 31.7,
    body: {
      intro: "Client intake done well means you start an engagement with the information you need instead of spending the first two weeks chasing it. This template covers the questions that actually matter — not a generic questionnaire, but a structured intake that surfaces the real situation before the first call.",
      whatYouGet: [
        "Client intake structure: current situation, the problem to solve, objectives and success criteria, constraints (budget, timeline, resources), and decision-making process",
        "Pre-send guide: how to frame the intake to get honest, complete answers",
        "AI prompt to generate a project brief from intake responses",
        "Worked example from a consulting engagement",
      ],
      whoItsFor: "Independent consultants and fractional executives who start new engagements regularly and want a consistent intake process that gets the right information before the work begins.",
      ctaNote: "Free template. To build a client intake tool that clients complete before engagement kick-off, the Torvi Consultant track covers it.",
    },
  },
  {
    slug: "ai-requirements-intake-tool",
    title: "AI Requirements Intake Tool — Guide | Torvi",
    h1: "AI requirements intake tool",
    metaDescription: "How to build an AI-powered requirements intake tool that asks clarifying questions and generates a structured requirements doc.",
    keyword: "ai requirements intake tool",
    cluster: "intake_and_routing",
    pageType: "template_page",
    priorityScore: 28.5,
    body: {
      intro: "Requirements intake is where vague ideas are supposed to become clear specifications. AI can accelerate that conversion — by asking the right clarifying questions, identifying gaps, and producing a structured requirements document from the answers.",
      whatYouGet: [
        "Requirements intake workflow: brief submission → AI clarification questions → requirements generation → review",
        "Clarifying question set for different requirement types: feature, integration, automation, reporting",
        "AI prompt to generate structured requirements from an intake brief",
        "Worked example for an internal tool requirements intake",
      ],
      whoItsFor: "PMs and technical leads who receive feature or tool requests from stakeholders and want a structured intake process that captures enough information to write good requirements without a 30-minute meeting.",
      ctaNote: "Free guide. To build an automated requirements intake tool for your team, the Torvi PM track walks you through it.",
    },
  },
  {
    slug: "project-intake-template",
    title: "Project Intake Template — Free Download | Torvi",
    h1: "Project intake template",
    metaDescription: "A lean project intake template for ops and PM teams. Problem, scope, owner, priority. Free download.",
    keyword: "project intake template",
    cluster: "intake_and_routing",
    pageType: "starter_pack",
    priorityScore: 25.0,
    body: {
      intro: "Every project starts with a request. Most requests are vague. This template forces clarity at the intake stage — so projects start with a defined problem, a defined scope, and a defined owner, instead of discovering all three six weeks in.",
      whatYouGet: [
        "Project intake form: problem statement, proposed solution, success criteria, scope boundaries, owner, estimated effort, and priority",
        "Intake review checklist: questions to ask before approving a project to start",
        "AI prompt to generate a project brief from intake responses",
        "Worked example for an ops team intake process",
      ],
      whoItsFor: "Operations managers and project leads who receive project requests from across the business and want to standardise the intake process so projects start with clarity instead of ambiguity.",
      ctaNote: "Free template. To automate your project intake process end to end, the Torvi Ops track gives you the four-week path to ship the tool.",
    },
  },
];
