import type { PSEOPage } from "../pages";

export const vibeCodingPages: PSEOPage[] = [
  {
    slug: "vibe-coding-for-product-managers",
    title: "Vibe Coding for Product Managers — Ship a Tool in 4 Weeks | Torvi",
    h1: "Vibe coding for product managers",
    metaDescription: "A 4-week guided build for product managers who want to ship an AI-powered work tool. No engineering team required. Open enrolment.",
    keyword: "vibe coding course for product managers",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 41.0,
    body: {
      intro: "Product managers write the specs. They rarely build the tools. Torvi gives PMs the guided path to ship one — from a one-page tool brief in Week 0 to a deployed, working tool in Week 4. Most PM track participants build something they use daily: a PRD generator, a stakeholder update tool, a meeting notes automator.",
      whatYouGet: [
        "Week 0: Write your tool brief. Define the problem, the user, and the scope.",
        "Weeks 1–4: PM-specific build path — prompt engineering, lightweight UI, integration with your stack",
        "Weekly office hours with practitioners who have shipped PM tooling in production",
        "A working tool you use every day — not a side project that lives in a folder",
      ],
      whoItsFor: "Product managers who use AI tools daily and want to go one level deeper — building something that saves their team real time, not just their own prompting workflow.",
      ctaNote: "Open enrolment, start immediately. Founding rate €200.",
    },
  },
  {
    slug: "ai-coding-training-for-product-managers",
    title: "AI Coding Training for Product Managers — Torvi",
    h1: "AI coding training for product managers",
    metaDescription: "Structured AI coding training for PMs who want to build and ship a work tool in 4 weeks. Guided, practical, outcome-first. Start now.",
    keyword: "ai coding training for product managers",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 46.7,
    body: {
      intro: "AI coding training for product managers means one thing in practice: going from 'I know what should be built' to 'I can build it.' Torvi's PM track is four weeks of structured, output-focused work. You will not watch lectures. You will build.",
      whatYouGet: [
        "Week 0: Tool brief — clear scope, defined problem, chosen stack",
        "Week 1: Core logic — the part of your tool that does the actual work",
        "Weeks 2–3: Interface and integration — making it usable by someone else",
        "Week 4: Ship — deployed, working, something you can show",
      ],
      whoItsFor: "Product managers who are comfortable describing what to build and want to develop the ability to build it themselves, using AI-native tooling and a structured weekly process.",
      ctaNote: "Open enrolment, start immediately. Four weeks, one shipped tool, founding rate €200.",
    },
  },
  {
    slug: "vibe-coding-workshop-for-product-management",
    title: "Vibe Coding Workshop for Product Management — Torvi",
    h1: "Vibe coding workshop for product management",
    metaDescription: "A structured vibe coding programme for product management professionals. Ship one AI tool in 4 weeks. Weekly guided runs. Start now.",
    keyword: "vibe coding workshop for product management",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 39.1,
    body: {
      intro: "Product management and AI tool building are increasingly the same job. This programme gives you the structured path to develop that capability — not as an academic exercise, but as a four-week build sprint that ends with a shipped tool.",
      whatYouGet: [
        "Structured build path from tool brief to deployed product",
        "PM-specific guidance on scoping, prompting, and shipping internal tools",
        "Weekly office hours for real-time unblocking (not asynchronous feedback threads)",
        "Certificate on completion — a credential that reflects a shipped output, not course completion",
      ],
      whoItsFor: "Product professionals who want to add 'I can build this' to their existing 'I can spec this' capability — without a computer science degree or an engineering team.",
      ctaNote: "Open enrolment. Buy now, start immediately. €200 founding rate.",
    },
  },
  {
    slug: "vibe-coding-for-product-lead",
    title: "Vibe Coding for Product Leads — Torvi",
    h1: "Build AI tools as a product lead",
    metaDescription: "A 4-week guided build for product leads who want to ship one AI-powered work tool. Open enrolment, start immediately.",
    keyword: "vibe coding workshop for product lead",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 34.8,
    body: {
      intro: "Product leads are expected to understand what is technically possible. Torvi gives you a faster, more direct path to that understanding — by actually building a tool, not by reading about it.",
      whatYouGet: [
        "Week 0: Define the tool you will build and why it matters for your team",
        "Weeks 1–4: Build the tool with a guided weekly structure and real office hours support",
        "Exposure to AI-native tooling (LLM APIs, prompt chaining, lightweight interfaces)",
        "A shipped tool and a certificate at the end — not a completion badge",
      ],
      whoItsFor: "Product leads who want hands-on experience with AI tool building — to make better product decisions, evaluate technical proposals more accurately, and build credibility with engineering.",
      ctaNote: "Open enrolment. Start when you are ready. Founding rate €200.",
    },
  },
  {
    slug: "ai-coding-training-with-cursor",
    title: "AI Coding Training with Cursor — Torvi",
    h1: "AI coding training with Cursor",
    metaDescription: "Learn to build and ship a work tool using Cursor AI. 4-week guided build for non-developers. Structured, practical, outcome-first.",
    keyword: "ai coding training with cursor",
    cluster: "vibe_coding_training",
    pageType: "role_page",
    priorityScore: 33.1,
    body: {
      intro: "Cursor has made it possible for non-developers to build real software — but most people hit a wall when moving from demo to something that actually works. Torvi gives you the structured path through that wall: a four-week guided build using Cursor, with office hours when you get stuck.",
      whatYouGet: [
        "Week 0: Tool scoping and Cursor setup — the environment, the model, the workflow",
        "Weeks 1–4: Guided build using Cursor for all implementation, with weekly review and unblocking",
        "Cursor-specific prompt techniques for internal tools and workflow automation",
        "A shipped tool at the end — not a tutorial project",
      ],
      whoItsFor: "Senior professionals who have tried Cursor and got partway but could not get to a working, deployed tool without an engineering team to lean on.",
      ctaNote: "Open enrolment. Four weeks. €200 founding rate. Cursor knowledge not required — you will develop it as part of the run.",
    },
  },
];
